function data = updateErrorbar(obj, plotIndex)
	%-get data structures-%
	plotData = obj.State.Plot(plotIndex).Handle;

	%-set trace-%
	data = updateLineseries(obj, plotIndex);

	data.error_y = struct( ...
		"visible", true, ...
		"type", "data", ...
		"array", plotData.YPositiveDelta, ...
		"arrayminus", plotData.YNegativeDelta, ...
		"thickness", plotData.LineWidth, ...
		"width", obj.PlotlyDefaults.ErrorbarWidth, ...
		"color", getStringColor(round(255*plotData.Color)), ...
		"symmetric", false ...
	);

	data.error_x = struct( ...
		"visible", true, ...
		"type", "data", ...
		"array", plotData.XPositiveDelta, ...
		"arrayminus", plotData.XNegativeDelta, ...
		"thickness", plotData.LineWidth, ...
		"width", obj.PlotlyDefaults.ErrorbarWidth, ...
		"color", getStringColor(round(255*plotData.Color)) ...
	);
end
