function data = updateErrorbarseries(obj, errorbarIndex)
    % type: ...[DONE]
    % symmetric: ...[DONE]
    % array: ...[DONE]
    % value: ...[NA]
    % arrayminus: ...{DONE]
    % valueminus: ...[NA]
    % color: ...[DONE]
    % thickness: ...[DONE]
    % width: ...[DONE]
    % opacity: ---[TODO]
    % visible: ...[DONE]
    errorbar_data = obj.State.Plot(errorbarIndex).Handle;

    data = updateLineseries(obj, errorbarIndex);
    data.error_y = struct( ...
        "visible", true, ...
        "type", "data", ...
        "symmetric", false, ...
        "array", errorbar_data.UData, ...
        "arrayminus", errorbar_data.LData, ...
        "thickness", errorbar_data.Children(2).LineWidth, ...
        "color", getStringColor(round(255*errorbar_data.Children(2).Color)), ...
        "width", obj.PlotlyDefaults.ErrorbarWidth ...
    );
end
