function data = updateErrorbarseries(obj, errorbarIndex)
    % type: ...[DONE]
    % symmetric: ...[DONE]
    % array: ...[DONE]
    % value: ...[NA]
    % arrayminus: ...{DONE]
    % valueminus: ...[NA]
    % color: ...[DONE]
    % thickness: ...[DONE]
    % width: ...[DONE]
    % opacity: ---[TODO]
    % visible: ...[DONE]
    errorbar_data = obj.State.Plot(errorbarIndex).Handle;

    tmpChildren = get(errorbar_data, 'Children');
    data = updateLineseries(obj, errorbarIndex);
    data.error_y = struct( ...
        "visible", true, ...
        "type", "data", ...
        "symmetric", false, ...
        "array", get(errorbar_data, 'UData'), ...
        "arrayminus", get(errorbar_data, 'LData'), ...
        "thickness", get(tmpChildren(2), 'LineWidth'), ...
        "color", getStringColor(round(255*get(tmpChildren(2), 'Color'))), ...
        "width", obj.PlotlyDefaults.ErrorbarWidth ...
    );
end
