function data = updateOnlyAxes(obj, plotIndex)
    %-AXIS INDEX-%
    axIndex = obj.getAxisIndex(obj.State.Plot(plotIndex).AssociatedAxis);

    %-CHECK FOR MULTIPLE AXES-%
    [xsource, ysource] = findSourceAxis(obj, axIndex);

    data = struct( ...
        "xaxis", sprintf("x%d", xsource), ...
        "yaxis", sprintf("y%d", ysource), ...
        "type", "scatter", ...
        "mode", "none", ...
        "x", [], ...
        "y", [], ...
        "name", "" ...
    );
end
