function data = updateErrorbar(obj, plotIndex)
	%-get data structures-%
	plotData = obj.State.Plot(plotIndex).Handle;

	%-set trace-%
	data = updateLineseries(obj, plotIndex);

	data.error_y = struct( ...
		"visible", true, ...
		"type", "data", ...
		"array", get(plotData, 'YPositiveDelta'), ...
		"arrayminus", get(plotData, 'YNegativeDelta'), ...
		"thickness", get(plotData, 'LineWidth'), ...
		"width", obj.PlotlyDefaults.ErrorbarWidth, ...
		"color", getStringColor(round(255*get(plotData, 'Color'))), ...
		"symmetric", false ...
	);

	data.error_x = struct( ...
		"visible", true, ...
		"type", "data", ...
		"array", get(plotData, 'XPositiveDelta'), ...
		"arrayminus", get(plotData, 'XNegativeDelta'), ...
		"thickness", get(plotData, 'LineWidth'), ...
		"width", obj.PlotlyDefaults.ErrorbarWidth, ...
		"color", getStringColor(round(255*get(plotData, 'Color'))) ...
	);
end
