function errormsg = apiv2msg(key)
switch key 
    case 'apiV2:noDomain'
        errormsg = ['\nOpps! It looks like you haven''t set up your Plotly '...
            'apiv2 domain configuration yet.\nTo get started, save your '...
            'plotly domain, streaming domain, and api domain by calling:\n'...
            '>>> saveplotlyconfig(plotly_domain, plotly_streaming_domain,',... 
            'plotly_api_domain). \n\nFor more help, see https://plot.ly/MATLAB',...
            'or contact chuck@plot.ly.\n\n'];
end