function figure = get_figure(file_owner, file_id)

    [un, key] = signin;

    headers = struct(...
                    'name',...
                        {...
                            'plotly-username',...
                            'plotly-apikey',...
                            'plotly-version',...
                            'plotly-platform',...
                            'user-agent'
                        },...
                    'value',...
                        {...
                            un,...
                            key,...
                            '1.0',...
                            'MATLAB',...
                            'MATLAB'
                        });

    url = ['https://plot.ly/apigetfile/', file_owner, '/', num2str(file_id)];

    [response, extras] = urlread2(url, 'Post', '', headers);

    response_handler(response, extras);

    response_object = loadjson(response);
    figure = response_object.payload.figure;
end