function gallery = makegallery(varargin)
    % MAKEGALLERY Create a single-page HTML gallery of Octave plot
    % functions. For every plot function, the gallery shows a PNG export of
    % the native Octave figure next to the converted Plotly figure.
    %
    % [CALL]:
    %   gallery = makegallery()
    %   gallery = makegallery('FileName', 'gallery.html')
    %   gallery = makegallery('Functions', {'plot' 'surf'})
    %   gallery = makegallery('OutputFolder', '/path/to/folder')
    %
    % [OPTIONS]: (Name, Value)
    %   FileName     - HTML file name. Default: 'plotly_gallery.html'
    %   OutputFolder - folder in which the HTML file is written.
    %                  Default: current working directory.
    %   Functions    - cellstr of plot function names to include.
    %                  Default: all supported functions.
    %   Visible      - 'off' (default) to keep the figures hidden while
    %                  the gallery is generated, 'on' to display them.
    %   EmbedPNG     - true (default) to embed the native PNGs in the
    %                  HTML as base64 data URIs (single self-contained
    %                  file), false to link to separate .png files.
    %   SavePNGs     - true to also write the native .png files next to
    %                  the HTML. Default: false.
    %   PlotlyJS     - 'auto' (default) to embed the local offline Plotly
    %                  bundle when available and fall back to the Plotly
    %                  CDN, 'bundle' to require the local bundle, 'cdn'
    %                  to always link the CDN, 'none' to skip Plotly.
    %   Theme        - 'dark' (default), 'light' or 'auto' (follow the
    %                  browser/system preference). A toggle button in the
    %                  gallery switches between dark and light at runtime.
    %   Open         - true (default) to open the gallery in the default
    %                  web browser once it has been written.
    %   Width,Height - maximum width and aspect ratio (Width:Height) of
    %                  the figure panels. The native PNGs and the Plotly
    %                  figures share the same size and shrink together
    %                  as the window narrows. Default: 640, 480
    %
    % [OUTPUT]:
    %   gallery - struct with the generated HTML file path, the Plotly JS
    %             source that was used, and the per-entry status of the
    %             native figure export and of the Plotly conversion.
    %
    % NOTE: the native PNG is exported from the Octave/MATLAB figure
    % object itself with print(); it is NOT taken from the converted
    % Plotly object.

    opts = parseOptions(varargin);

    % % load the statistics package on Octave (boxplot, bar3, bar3h etc.)
    if is_octave()
        try
            pkg load statistics;
        catch
        end
    end

    if isempty(which('plotlyfig'))
        warning('makegallery:noPlotlyfig', ...
            ['plotlyfig was not found on the MATLAB/Octave path. ' ...
            'Run plotlysetup_offline() first; the Plotly panels will ' ...
            'report conversion errors.']);
    end

    allEntries = galleryEntries();
    if isempty(opts.Functions)
        names = allEntries(:, 1);
    else
        requested = cellstr(opts.Functions);
        ok = ismember(requested, allEntries(:, 1));
        if ~all(ok)
            error('makegallery:unknownFunction', ...
                'Unknown plot function(s): %s. Valid names are: %s', ...
                strjoin(requested(~ok), ', '), ...
                strjoin(allEntries(:, 1), ', '));
        end
        names = requested;
    end

    fprintf('Generating Plotly gallery with %d entries ...\n', numel(names));

    js = resolvePlotlyJS(lower(opts.PlotlyJS));

    entries = processEntries(names, allEntries, opts);

    parts = htmlHeader(opts, js, numel(entries));
    parts{end + 1} = htmlSummary(entries);
    for i = 1:numel(entries)
        parts = [parts htmlEntry(entries(i), i, opts)];
    end
    parts{end + 1} = sprintf('</body>\n</html>\n');

    page = char(strjoin(cellfun(@flattenChar, parts, 'UniformOutput', false), ''));

    htmlPath = fullfile(opts.OutputFolder, opts.FileName);
    fid = fopen(htmlPath, 'w');
    fwrite(fid, page);
    fclose(fid);

    gallery.html = htmlPath;
    gallery.outputFolder = opts.OutputFolder;
    gallery.plotlyJS = js.mode;
    gallery.entries = entries;
    gallery.summary = struct( ...
        'total', numel(entries), ...
        'nativeOK', sum([entries.nativeOK]), ...
        'plotlyOK', sum([entries.plotlyOK]) ...
    );

    fprintf('\nGallery written to: %s\n', htmlPath);
    fprintf('  %d/%d native figure exports OK, %d/%d Plotly conversions OK\n', ...
        gallery.summary.nativeOK, gallery.summary.total, ...
        gallery.summary.plotlyOK, gallery.summary.total);

    if opts.Open
        web(htmlPath);
    end
end

function opts = parseOptions(varargs)
    opts = struct( ...
        'FileName', 'plotly_gallery.html', ...
        'OutputFolder', pwd, ...
        'Functions', {{}}, ...
        'Visible', 'off', ...
        'EmbedPNG', true, ...
        'SavePNGs', false, ...
        'PlotlyJS', 'auto', ...
        'Theme', 'dark', ...
        'Open', true, ...
        'Width', 640, ...
        'Height', 480 ...
    );

    for a = 1:2:numel(varargs)
        property = lower(varargs{a});
        value = varargs{a + 1};
        switch property
            case 'filename'
                opts.FileName = value;
            case 'outputfolder'
                opts.OutputFolder = value;
            case 'functions'
                opts.Functions = value;
            case 'visible'
                opts.Visible = value;
            case 'embedpng'
                opts.EmbedPNG = value;
            case 'savepngs'
                opts.SavePNGs = value;
            case 'plotlyjs'
                opts.PlotlyJS = value;
            case 'theme'
                opts.Theme = value;
            case 'open'
                opts.Open = value;
            case 'width'
                opts.Width = value;
            case 'height'
                opts.Height = value;
            otherwise
                error('makegallery:invalidOption', ...
                    'Unknown option: %s', varargs{a});
        end
    end

    if ~ismember(lower(opts.PlotlyJS), {'auto' 'bundle' 'cdn' 'none'})
        error('makegallery:invalidPlotlyJS', ...
            'PlotlyJS must be one of: auto, bundle, cdn, none');
    end
    if ~ismember(lower(opts.Visible), {'on' 'off'})
        error('makegallery:invalidVisible', ...
            'Visible must be ''on'' or ''off''');
    end
    if ~ismember(lower(opts.Theme), {'dark' 'light' 'auto'})
        error('makegallery:invalidTheme', ...
            'Theme must be one of: dark, light, auto');
    end
    if ~endsWith(opts.FileName, '.html', 'IgnoreCase', true)
        opts.FileName = [opts.FileName '.html'];
    end
    if ~exist(opts.OutputFolder, 'dir')
        mkdir(opts.OutputFolder);
    end
end

function entries = processEntries(names, allEntries, opts)
    entries = struct( ...
        'name', {}, 'code', {}, ...
        'nativeOK', {}, 'plotlyOK', {}, ...
        'nativeError', {}, 'plotlyError', {}, ...
        'plotlyStack', {}, ...
        'image', {}, 'pngFile', {}, ...
        'plotlyJSON', {} ...
    );

    for i = 1:numel(names)
        name = names{i};
        idx = find(strcmp(allEntries(:, 1), name), 1);
        code = allEntries{idx, 2};

        entry = struct( ...
            'name', name, 'code', code, ...
            'nativeOK', false, 'plotlyOK', false, ...
            'nativeError', '', 'plotlyError', '', ...
            'plotlyStack', '', ...
            'image', '', 'pngFile', '', ...
            'plotlyJSON', struct() ...
        );

        fig = figure('Visible', opts.Visible, 'Position', [0 0 640 480]);
        try
            eval(code);
            drawnow;
        catch e
            entry.nativeError = e.message;
        end

        % NOTE: the export must come from the native figure handle via
        % print(); it must NOT come from the converted Plotly object.
        if isempty(entry.nativeError)
            pngName = sprintf('%02d_%s.png', i, name);
            if opts.EmbedPNG && ~opts.SavePNGs
                pngPath = [tempname() '.png'];
                deleteTmp = true;
            else
                pngPath = fullfile(opts.OutputFolder, pngName);
                deleteTmp = false;
            end
            try
                if is_octave()
                    % print() renders the PNG at the figure's
                    % __device_pixel_ratio__; on HiDPI displays that
                    % doubles the -S size (e.g. 1280x960 from 640x480).
                    % Temporarily force a ratio of 1 so the PNG comes
                    % out at exactly the requested size on any display
                    dpr = [];
                    try
                        dpr = get(fig, '__device_pixel_ratio__');
                        set(fig, '__device_pixel_ratio__', 1);
                    catch
                    end
                    print(fig, '-dpng', '-S640,480', pngPath);
                    if ~isempty(dpr)
                        try
                            set(fig, '__device_pixel_ratio__', dpr);
                        catch
                        end
                    end
                else
                    print(fig, '-dpng', pngPath);
                end
                fid = fopen(pngPath, 'rb');
                pngBytes = fread(fid, Inf, 'uint8')';
                fclose(fid);
                if deleteTmp
                    delete(pngPath);
                end
                entry.image = base64DataURI(pngBytes);
                entry.pngFile = pngName;
                entry.nativeOK = true;
            catch e
                entry.nativeError = e.message;
            end
        end

        if entry.nativeOK
            try
                p = plotlyfig(fig, 'visible', 'off');
                % plotlyfig sets autosize to false and stores a fixed
                % pixel size (1.5x the figure) in the layout. With both
                % width and height set, Plotly's responsive mode never
                % resizes the figure, so it cannot track its HTML
                % container. Enable autosize and drop the fixed size so
                % the figure fills the container instead; the container
                % CSS below matches the native PNG's shape
                layout = p.layout;
                if isfield(layout, 'width')
                    layout = rmfield(layout, 'width');
                end
                if isfield(layout, 'height')
                    layout = rmfield(layout, 'height');
                end
                layout.autosize = true;
                entry.plotlyJSON = struct( ...
                    'data', jsonForScript(m2json(p.data)), ...
                    'layout', jsonForScript(m2json(layout)) ...
                );
                entry.plotlyOK = true;
            catch e
                entry.plotlyError = e.message;
                entry.plotlyStack = '';
                for st = 1:numel(e.stack)
                    entry.plotlyStack = [entry.plotlyStack ...
                        sprintf('%s (line %d)\n', e.stack(st).name, e.stack(st).line)];
                end
            end
        end
        if ~entry.plotlyOK && isempty(entry.plotlyError)
            entry.plotlyError = 'Skipped because the native figure export failed.';
        end

        try
            close(fig);
        catch
        end

        entries(i) = entry;

        fprintf('  %-14s native: %-6s plotly: %-6s\n', name, ...
            tern(entry.nativeOK, 'OK', 'FAIL'), ...
            tern(entry.plotlyOK, 'OK', 'FAIL'));
        if ~entry.plotlyOK && ~isempty(entry.plotlyError)
            fprintf('      plotly error: %s\n', entry.plotlyError);
            if ~isempty(entry.plotlyStack)
                fprintf('      stack:\n%s', entry.plotlyStack);
            end
        end
    end
end

function parts = htmlHeader(opts, js, nEntries)
    if is_octave()
        try
            runtime = sprintf('%s (%s graphics toolkit)', ...
                version(), graphics_toolkit());
        catch
            runtime = version();
        end
    else
        runtime = version();
    end

    % the embedded bundle must never pass through sprintf/fprintf, which
    % would interpret backslash sequences inside the JavaScript
    if js.embedded
        jsTag = ['<script type="text/javascript">' sprintf('\n') ...
            js.script sprintf('\n</script>\n')];
    elseif ~isempty(js.script)
        jsTag = ['<script src="' js.script '"></script>' sprintf('\n')];
    else
        jsTag = '';
    end

    % the figure panel size is defined once below (:root variables);
    % the page width, the PNG cap and the Plotly containers all derive
    % from it, so changing Width/Height needs no other edits. The theme
    % colors are CSS variables set per data-theme on the <html> element.
    fmt = [ ...
        '<!DOCTYPE html>\n' ...
        '<html lang="en" data-theme="%s">\n' ...
        '<head>\n' ...
        '<meta charset="utf-8">\n' ...
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n' ...
        '<title>Octave Plotly Gallery</title>\n' ...
        '<style>\n' ...
        ':root { --fig-width: %d; --fig-height: %d; ' ...
        '--panel-gap: 16px; --page-padding: 24px; }\n' ...
        ':root[data-theme="dark"] { ' ...
        '--bg: #1f2328; --fg: #f0f3f6; --muted: #8b949e; --border: #3d444d; ' ...
        '--panel: #2d333b; --code: #161b22; --th: #22272e; ' ...
        '--ok: #3fb950; --fail: #f85149; ' ...
        '--chip-ok-bg: #1a3328; --chip-ok-fg: #3fb950; ' ...
        '--chip-fail-bg: #3d1c1c; --chip-fail-fg: #f85149; ' ...
        '--err-bg: #2d1515; --err-border: #6e2222; --img-bg: #ffffff; }\n' ...
        ':root[data-theme="light"] { ' ...
        '--bg: #f6f8fa; --fg: #1f2328; --muted: #57606a; --border: #d0d7de; ' ...
        '--panel: #ffffff; --code: #f6f8fa; --th: #eaeef2; ' ...
        '--ok: #116329; --fail: #cf222e; ' ...
        '--chip-ok-bg: #dafbe1; --chip-ok-fg: #116329; ' ...
        '--chip-fail-bg: #ffebe9; --chip-fail-fg: #cf222e; ' ...
        '--err-bg: #fff5f5; --err-border: #ffcecb; --img-bg: #ffffff; }\n' ...
        'body { box-sizing: border-box; ' ...
        'max-width: calc(2 * var(--fig-width) * 1px + var(--panel-gap) + 2 * var(--page-padding)); ' ...
        'font-family: system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif; ' ...
        'margin: 0; padding: var(--page-padding); background: var(--bg); color: var(--fg); }\n' ...
        'h1 { margin: 0 0 4px; }\n' ...
        '.subtitle { color: var(--muted); margin: 0 0 20px; }\n' ...
        '.theme-toggle { border: 1px solid var(--border); background: var(--panel); ' ...
        'color: var(--fg); border-radius: 6px; padding: 6px 12px; cursor: pointer; ' ...
        'font-size: 13px; margin: 0 0 20px; }\n' ...
        '.theme-toggle:hover { border-color: var(--muted); }\n' ...
        '.summary { border-collapse: collapse; margin: 0 0 24px; font-size: 13px; }\n' ...
        '.summary th, .summary td { border: 1px solid var(--border); ' ...
        'padding: 3px 10px; text-align: left; }\n' ...
        '.summary th { background: var(--th); }\n' ...
        '.ok { color: var(--ok); }\n' ...
        '.fail { color: var(--fail); }\n' ...
        '.entry { background: var(--panel); border: 1px solid var(--border); ' ...
        'border-radius: 8px; padding: 16px; margin-bottom: 24px; }\n' ...
        '.entry h2 { margin: 0 0 8px; font-size: 18px; }\n' ...
        '.chip { display: inline-block; padding: 2px 10px; border-radius: 999px; ' ...
        'font-size: 12px; margin-left: 6px; vertical-align: middle; }\n' ...
        '.chip.ok { background: var(--chip-ok-bg); color: var(--chip-ok-fg); }\n' ...
        '.chip.fail { background: var(--chip-fail-bg); color: var(--chip-fail-fg); }\n' ...
        '.codebox { background: var(--code); border: 1px solid var(--border); ' ...
        'border-radius: 6px; padding: 10px; ' ...
        'font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; ' ...
        'font-size: 13px; overflow-x: auto; margin: 8px 0 12px; }\n' ...
        '.panels { display: grid; grid-template-columns: repeat(auto-fit, minmax(340px, 1fr)); ' ...
        'gap: var(--panel-gap); }\n' ...
        '.panel h3 { margin: 0 0 8px; font-size: 14px; color: var(--muted); font-weight: 600; }\n' ...
        '.panel img { max-width: min(100%%, calc(var(--fig-width) * 1px)); ' ...
        'border: 1px solid var(--border); border-radius: 6px; background: var(--img-bg); }\n' ...
        '.err { color: var(--fail); font-size: 13px; white-space: pre-wrap; ' ...
        'background: var(--err-bg); border: 1px solid var(--err-border); ' ...
        'border-radius: 6px; padding: 8px; }\n' ...
        '.plotlybox { width: 100%%; max-width: calc(var(--fig-width) * 1px); ' ...
        'aspect-ratio: var(--fig-width) / var(--fig-height); }\n' ...
        '</style>\n' ...
        '</head>\n' ...
        '<body>\n' ...
        '<h1>Octave plot functions &rarr; Plotly gallery</h1>\n' ...
        '<p class="subtitle">Generated %s with %s &middot; %d plot functions &middot; ' ...
        'Plotly JS: %s &middot; The PNGs are exported from the native Octave figures ' ...
        'with print(), not from the converted Plotly objects.</p>\n' ...
        '<button id="theme-toggle" class="theme-toggle" type="button">Toggle theme</button>\n' ...
    ];

    % resolve the 'auto' theme from the system preference and wire the
    % toggle button; sprintf processes the \n escapes, and the script
    % has no % characters so sprintf leaves it intact
    themeScript = sprintf(['<script>\n' ...
        '(function () {\n' ...
        '  var root = document.documentElement;\n' ...
        '  if (root.dataset.theme === "auto") {\n' ...
        '    var mq = window.matchMedia("(prefers-color-scheme: dark)");\n' ...
        '    var apply = function () { root.dataset.theme = mq.matches ? "dark" : "light"; };\n' ...
        '    apply();\n' ...
        '    mq.addEventListener("change", apply);\n' ...
        '  }\n' ...
        '  document.getElementById("theme-toggle").addEventListener("click", function () {\n' ...
        '    root.dataset.theme = root.dataset.theme === "dark" ? "light" : "dark";\n' ...
        '  });\n' ...
        '})();\n' ...
        '</script>\n']);

    parts = {sprintf(fmt, lower(char(opts.Theme)), opts.Width, opts.Height, ...
        datestr(now), runtime, nEntries, js.mode), jsTag, themeScript};
end

function str = htmlSummary(entries)
    fmt = ['<table class="summary">\n' ...
        '<thead><tr><th>function</th><th>native figure</th><th>plotly</th></tr></thead>\n' ...
        '<tbody>\n'];
    str = sprintf(fmt);
    rowFmt = ['<tr><td><a href="#fn-%s">%s</a></td><td>%s</td><td>%s</td></tr>\n'];
    for i = 1:numel(entries)
        nativeChip = tern(entries(i).nativeOK, ...
            '<span class="ok">OK</span>', '<span class="fail">FAIL</span>');
        plotlyChip = tern(entries(i).plotlyOK, ...
            '<span class="ok">OK</span>', '<span class="fail">FAIL</span>');
        str = [str sprintf(rowFmt, entries(i).name, entries(i).name, ...
            nativeChip, plotlyChip)];
    end
    str = [str sprintf('</tbody>\n</table>\n')];
end

function parts = htmlEntry(entry, i, opts)
    parts = {};

    parts{end + 1} = sprintf('<section class="entry" id="fn-%s">\n', entry.name);
    parts{end + 1} = sprintf('<h2><code>%s</code>', entry.name);
    parts{end + 1} = chipTag(entry.nativeOK, 'native');
    parts{end + 1} = chipTag(entry.plotlyOK, 'plotly');
    parts{end + 1} = sprintf('</h2>\n');

    % htmlEscape output is appended by concatenation, never through
    % sprintf, to keep backslash characters in the escaped text intact
    parts{end + 1} = [sprintf('<pre class="codebox"><code>') ...
        htmlEscape(entry.code) sprintf('</code></pre>\n')];
    parts{end + 1} = sprintf('<div class="panels">\n');

    parts{end + 1} = sprintf(['<div class="panel">\n' ...
        '<h3>Octave figure (native PNG export)</h3>\n']);
    if entry.nativeOK
        if opts.EmbedPNG
            parts{end + 1} = [sprintf('<img src="') entry.image ...
                sprintf('" alt="%s native figure">\n', entry.name)];
        else
            parts{end + 1} = [sprintf('<img src="') entry.pngFile ...
                sprintf('" alt="%s native figure">\n', entry.name)];
        end
    else
        parts{end + 1} = [sprintf('<p class="err">') ...
            htmlEscape(entry.nativeError) sprintf('</p>\n')];
    end
    parts{end + 1} = sprintf('</div>\n');

    parts{end + 1} = sprintf(['<div class="panel">\n' ...
        '<h3>Plotly figure</h3>\n']);
    if entry.plotlyOK
        divId = sprintf('plotly-%d', i);
        % the container is sized purely by CSS like the native PNG: it
        % fills the panel width, capped at the --fig-width variable with
        % the --fig-width/--fig-height shape. The layout has no fixed
        % pixel size, so Plotly's responsive mode follows the container
        divFmt = ['<div id="%s" class="plotlybox"></div>\n'];
        parts{end + 1} = sprintf(divFmt, divId);

        % the JSON comes from m2json(); it is appended with char
        % concatenation, never through sprintf, so that backslash
        % sequences inside the JSON survive untouched
        scriptPart = [sprintf('<script type="text/javascript">\n') ...
            sprintf('Plotly.newPlot("%s", ', divId) ...
            entry.plotlyJSON.data [', '] entry.plotlyJSON.layout ...
            sprintf(', {"responsive": true});\n</script>\n')];
        parts{end + 1} = scriptPart;
    else
        parts{end + 1} = [sprintf('<p class="err">') ...
            htmlEscape(entry.plotlyError) sprintf('</p>\n')];
        if ~isempty(entry.plotlyStack)
            parts{end + 1} = [sprintf('<pre class="err">') ...
                htmlEscape(entry.plotlyStack) sprintf('</pre>\n')];
        end
    end
    parts{end + 1} = sprintf('</div>\n');

    parts{end + 1} = sprintf('</div>\n');
    parts{end + 1} = sprintf('</section>\n\n');
end

function chip = chipTag(ok, label)
    if ok
        chip = sprintf('<span class="chip ok">%s OK</span>', label);
    else
        chip = sprintf('<span class="chip fail">%s FAIL</span>', label);
    end
end

function json = jsonForScript(rawJson)
    % make the m2json output safe to embed inside a <script> element:
    % replace real line breaks with JSON escapes and break up any
    % "</script" sequence that would close the element prematurely
    json = strrep(strrep(rawJson, sprintf('\n'), '\n'), sprintf('\r'), '\r');
    json = strrep(json, '</script', '<\/script');
end

function js = resolvePlotlyJS(mode)
    js.mode = mode;
    js.script = '';
    js.embedded = false;

    if strcmpi(mode, 'cdn')
        js.mode = 'cdn';
        js.script = 'https://cdn.plot.ly/plotly-latest.min.js';
    elseif strcmpi(mode, 'bundle') || strcmpi(mode, 'auto')
        % look for the local offline bundle (same location as plotlyoffline)
        bundleFile = fullfile(userHome(), '.plotly', 'plotlyjs', ...
            'plotly-matlab-offline-bundle.js');
        if exist(bundleFile, 'file')
            try
                js.mode = 'bundle';
                js.script = readBundle(bundleFile);
                js.embedded = true;
                return;
            catch
            end
        end
        if strcmpi(mode, 'bundle')
            error('makegallery:bundleNotFound', ...
                ['Offline Plotly bundle not found at: %s. ' ...
                'Run getplotlyoffline() first.'], bundleFile);
        end
        js.mode = 'cdn';
        js.script = 'https://cdn.plot.ly/plotly-latest.min.js';
    end
end

function bundle = readBundle(bundleFile)
    % read the offline Plotly bundle. Bundles saved by getplotlyoffline
    % were pre-escaped for sprintf with escapechars (every '%' and every
    % backslash was doubled); detect that and undo it so the browser
    % receives the byte-accurate JavaScript. Raw bundles are returned
    % unchanged.
    bundle = fileread(bundleFile);
    c = uint8(bundle);
    isPct = c == uint8('%');
    isBk = c == uint8('\');
    nextPct = [isPct(2:end) false];
    nextBk = [isBk(2:end) false];
    prevPct = [false isPct(1:end - 1)];
    prevBk = [false isBk(1:end - 1)];
    singlePct = isPct & ~nextPct & ~prevPct;
    singleBk = isBk & ~nextBk & ~prevBk;
    if any(singlePct) || any(singleBk)
        return;
    end
    % regexprep matches non-overlapping pairs, unlike strrep which would
    % re-match on the doubled text and collapse pairs too far
    bundle = regexprep(bundle, '%%', char(1));
    bundle = regexprep(bundle, '\\\\', char(2));
    bundle = strrep(bundle, char(1), '%');
    bundle = strrep(bundle, char(2), '\');
end

function d = userHome()
    if is_octave()
        d = getenv('HOME');
        if isempty(d)
            d = getenv('USERPROFILE');
        end
    else
        try
            d = char(java.lang.System.getProperty('user.home'));
        catch
            d = getenv('USERPROFILE');
        end
    end
end

function row = flattenChar(p)
    % strjoin requires every element to be a char row vector; strings
    % and cells convert to padded char matrices, so flatten afterwards
    if iscell(p) || isstring(p)
        p = char(p);
    end
    row = p(:)';
end

function clean = htmlEscape(str)
    clean = strrep(str, '&', '&amp;');
    clean = strrep(clean, '<', '&lt;');
    clean = strrep(clean, '>', '&gt;');
    clean = strrep(clean, '"', '&quot;');
end

function uri = base64DataURI(bytes)
    uri = ['data:image/png;base64,' base64Encode(bytes)];
end

function b64 = base64Encode(bytes)
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    n = numel(bytes);
    if n == 0
        b64 = '';
        return;
    end
    pad = mod(3 - mod(n, 3), 3);
    b = reshape([bytes(:); zeros(pad, 1)], 3, []);
    idx = zeros(4, size(b, 2));
    idx(1, :) = bitshift(b(1, :), -2) + 1;
    idx(2, :) = bitshift(bitand(b(1, :), 3), 4) + bitshift(b(2, :), -4) + 1;
    idx(3, :) = bitshift(bitand(b(2, :), 15), 2) + bitshift(b(3, :), -6) + 1;
    idx(4, :) = bitand(b(3, :), 63) + 1;
    b64 = char(alphabet(idx));
    b64 = b64(:)';
    if pad > 0
        b64(end - pad + 1:end) = '=';
    end
end

function out = tern(cond, a, b)
    if cond
        out = a;
    else
        out = b;
    end
end

function entries = galleryEntries()
    entries = { ...
        'plot',        'x = 0:0.05:2*pi; plot(x, sin(x), ''b'', x, cos(x), ''r--'');'; ...
        'plot3',       't = 0:0.05:6*pi; plot3(sin(t), cos(t), t);'; ...
        'semilogx',    'x = logspace(-2, 2, 200); semilogx(x, 1 ./ sqrt(1 + x.^2));'; ...
        'semilogy',    'x = logspace(-1, 1, 200); semilogy(x, exp(x));'; ...
        'loglog',      'x = logspace(-1, 1, 200); loglog(x, x.^2);'; ...
        'loglogerr',   'x = logspace(0, 1, 10); y = x.^2; err = 0.4*y; loglogerr(x, y, err);'; ...
        'semilogxerr', 'x = logspace(-2, 1, 50); y = x.^(-0.5) .* sin(2*pi*log10(x)); err = 0.2 * y; semilogxerr(x, y, err);'; ...
        'semilogyerr', 'x = 0:0.5:20; y = 10 * exp(-0.3*x) .* (1 + 0.15*randn(size(x))); err = 0.2 * y; semilogyerr(x, y, err);'; ...
        'polar',       't = 0:0.01:2*pi; polar(t, 1 + 0.5*sin(3*t));'; ...
        'plotyy',      'x = 0:0.1:10; plotyy(x, sin(x), x, 100*cos(x));'; ...
        'bar',         'bar(1:10, [3 5 2 8 4 6 9 1 7 5]);'; ...
        'barh',        'barh(1:10, [3 5 2 8 4 6 9 1 7 5]);'; ...
        'bar3',        'bar3(peaks(5)/10);'; ...
        'bar3h',       'bar3h(peaks(5)/10);'; ...
        'hist',        'x = randn(10000, 1); hist(x, 30);'; ...
        'histogram',   'x = randn(10000, 1); histogram(x, 30);'; ...
        'rose',        'x = randn(5000, 1)*2*pi; rose(x, 20);'; ...
        'stairs',      'x = 0:0.5:10; stairs(x, sin(x));'; ...
        'stem',        'x = 0:0.1:2*pi; stem(x, sin(x));'; ...
        'stem3',       't = 0:0.2:6*pi; stem3(cos(t), sin(t), t);'; ...
        'scatter',     'x = randn(200, 1); y = randn(200, 1); scatter(x, y);'; ...
        'scatter3',    '[x, y, z] = sphere(20); scatter3(x(:), y(:), z(:));'; ...
        'pie',         'pie([3 5 2 4 6]);'; ...
        'pie3',        'pie3([3 5 2 4 6]);'; ...
        'compass',     't = 0:pi/8:2*pi; compass(cos(t), sin(t));'; ...
        'feather',     't = 0:pi/8:2*pi; feather(sin(t), cos(t));'; ...
        'quiver',      '[x, y] = meshgrid(-3:0.5:3); quiver(x, y, sin(x), cos(y));'; ...
        'quiver3',     '[x, y, z] = meshgrid(-1:0.5:1); quiver3(x, y, z, sin(x), cos(y), z);'; ...
        'area',        'area(1:10, [3 5 2 8 4 6 9 1 7 5]);'; ...
        'errorbar',    'x = 1:10; errorbar(x, [3 5 2 8 4 6 9 1 7 5], 0.5*ones(1, 10));'; ...
        'fill',        'x = 0:0.1:2*pi; fill(x, sin(x), ''g'');'; ...
        'fill3',       '[x, y, z] = sphere(20); fill3(x(1:10, :), y(1:10, :), z(1:10, :), ''y'');'; ...
        'image',       'image(rand(64, 64)*255);'; ...
        'imagesc',     'imagesc(rand(64, 64));'; ...
        'spy',         'spy(sprandn(50, 50, 0.1));'; ...
        'pcolor',      '[x, y, z] = peaks(30); pcolor(x, y, z); shading flat;'; ...
        'contour',     '[x, y, z] = peaks(30); contour(x, y, z, 10);'; ...
        'contourf',    '[x, y, z] = peaks(30); contourf(x, y, z, 10);'; ...
        'contour3',    '[x, y, z] = peaks(30); contour3(x, y, z, 10);'; ...
        'mesh',        '[x, y, z] = peaks(30); mesh(x, y, z);'; ...
        'meshc',       '[x, y, z] = peaks(30); meshc(x, y, z);'; ...
        'meshz',       '[x, y, z] = peaks(30); meshz(x, y, z);'; ...
        'surf',        '[x, y, z] = peaks(30); surf(x, y, z);'; ...
        'surfc',       '[x, y, z] = peaks(30); surfc(x, y, z);'; ...
        'surfl',       '[x, y, z] = peaks(30); surfl(x, y, z);'; ...
        'waterfall',   '[x, y, z] = peaks(30); waterfall(x, y, z);'; ...
        'ribbon',      "t = 0:0.1:10; y = [sin(t); cos(t)]'; ribbon(t, y);"; ...
        'slice',       '[x, y, z] = meshgrid(-2:0.5:2); v = x.*exp(-x.^2 - y.^2 - z.^2); slice(x, y, z, v, 0, 0, 0);'; ...
        'trisurf',     '[x, y, z] = peaks(30); trisurf(delaunay(x(:), y(:)), x(:), y(:), z(:));'; ...
        'trimesh',     '[x, y, z] = peaks(30); trimesh(delaunay(x(:), y(:)), x(:), y(:), z(:));'; ...
        'tetramesh',   'X = rand(20, 3); T = delaunayn(X); tetramesh(T, X);'; ...
        'patch',       't = 0:2*pi/5:2*pi; patch(cos(t), sin(t), ''b'');'; ...
        'rectangle',   'rectangle(''Position'', [0 0 2 3], ''FaceColor'', ''r'');'; ...
        'line',        'line([0 1 2], [0 1 0], ''LineWidth'', 2);'; ...
        'ezplot',      'ezplot(''sin(x)*cos(x)'', [-2*pi 2*pi]);'; ...
        'ezplot3',     'ezplot3(''sin(t)'', ''cos(t)'', ''t'', [0 6*pi]);'; ...
        'ezpolar',     'ezpolar(''1 + cos(t)'');'; ...
        'ezcontour',   'ezcontour(''sin(x)*cos(y)'', [-3 3]);'; ...
        'ezcontourf',  'ezcontourf(''sin(x)*cos(y)'', [-3 3]);'; ...
        'ezmesh',      'ezmesh(''sin(x)*cos(y)'', [-3 3]);'; ...
        'ezmeshc',     'ezmeshc(''sin(x)*cos(y)'', [-3 3]);'; ...
        'ezsurf',      'ezsurf(''sin(x)*cos(y)'', [-3 3]);'; ...
        'ezsurfc',     'ezsurfc(''sin(x)*cos(y)'', [-3 3]);'; ...
        'fplot',       'fplot(@(x) sin(x) + cos(x), [-3 3]);'; ...
        'fplot3',      'fplot3(@(t) sin(t), @(t) cos(t), @(t) t, [0 6*pi]);'; ...
        'fmesh',       'fmesh(@(x, y) sin(x).*cos(y), [-3 3]);'; ...
        'fsurf',       'fsurf(@(x, y) sin(x).*cos(y), [-3 3]);'; ...
        'fcontour',    'fcontour(@(x, y) sin(x).*cos(y), [-3 3]);'; ...
        'fimplicit',   'fimplicit(@(x, y) x.^2 + y.^2 - 4);'; ...
        'fimplicit3',  'fimplicit3(@(x, y, z) x.^2 + y.^2 + z.^2 - 4);'; ...
        'plotmatrix',  'plotmatrix(randn(100, 3));'; ...
        'voronoi',     'x = randn(30, 1); y = randn(30, 1); voronoi(x, y);'; ...
        'convhull',    'x = randn(30, 1); y = randn(30, 1); k = convhull(x, y); plot(x(k), y(k), ''b-'', x, y, ''r.'');'; ...
        'sombrero',    'sombrero();'; ...
        'peaks',       'peaks();'; ...
        'sphere',      'sphere(30);'; ...
        'cylinder',    'cylinder(1:0.1:2, 30);'; ...
        'ellipsoid',   'ellipsoid(0, 0, 0, 1, 2, 0.5, 30);'; ...
        'isosurface',  '[x, y, z] = meshgrid(-2:0.5:2); v = x.*exp(-x.^2 - y.^2 - z.^2); isosurface(x, y, z, v, 0.05);'; ...
        'streamline',  '[x, y] = meshgrid(-2:0.3:2); streamline(x, y, -y, x, [-1.5 -0.5 0.5 1.5], [1 1 1 1]);'; ...
        'boxplot',     'boxplot(randn(100, 4));' ...
    };
end
