classdef Test_plotlyfig_special < PlotlyTestCase
    methods
        function testPolarScatterData(tc)
            if is_octave()
                return % The `polarscatter` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            t = pi/4:pi/4:2*pi;
            r = [19 6 12 18 16 11 15 15];
            polarscatter(t,r)

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "subplot", 'polar2', ...
                "type", 'scatterpolar', ...
                "visible", true, ...
                "name", '', ...
                "r", r, ...
                "theta", rad2deg(t), ...
                "mode", 'markers', ...
                "marker", struct( ...
                    "sizeref", 1, ...
                    "sizemode", "area", ...
                    "size", [36 36 36 36 36 36 36 36], ...
                    "line", struct( ...
                        "width", 0.75, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "symbol", "circle", ...
                    "color", "rgba(0,0,0,0)", ...
                    "opacity", 1 ...
                ), ...
                "showlegend", true ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testPolarPlotData(tc)
            if is_octave()
                return % The `polarplot` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            t = 0:0.01:2*pi;
            r = abs(sin(2*t).*cos(2*t));
            polarplot(t, r)

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "subplot", 'polar2', ...
                "type", 'scatterpolar', ...
                "visible", true, ...
                "name", '', ...
                "r", r, ...
                "theta", rad2deg(t), ...
                "mode", 'lines', ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 1, ...
                    "dash", "solid" ...
                ), ...
                "showlegend", true ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testComplexPolarPlotData(tc)
            if is_octave()
                return % The `polarplot` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            Z = [2+3i 2 -1+4i 3-4i 5+2i -4-2i -2+3i -2 -3i 3i-2i];
            polarplot(Z,'*')

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "subplot", 'polar2', ...
                "type", 'scatterpolar', ...
                "visible", true, ...
                "name", '', ...
                "r", fig.Children.Children.RData, ...
                "theta", rad2deg(fig.Children.Children.ThetaData), ...
                "mode", 'markers', ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "symbol", "asterisk-open", ...
                    "maxdisplayed", 11, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct(), ...
                "showlegend", true ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testPolarHistogramPlotData(tc)
            if is_octave()
                return % The `polarhistogram` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            values = [0.6297 0.9559 0.7551 0.5261 0.8501 0.8160 0.1321 0.7607 0.6172 0.3976];
            polarhistogram(values);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", "barpolar", ...
                "r", [1 6 3 0], ...
                "width", [22.5 22.5 22.5 22.5], ...
                "theta", [11.25 33.75 56.25 78.75], ...
                "name", 'values', ...
                "marker", struct( ...
                    "line", struct( ...
                        "width", 0.5, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "opacity", 0.6, ...
                "visible", true, ...
                "subplot", PlotlyTestCase.Any(), ...
                "showlegend", true ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testEasyToUsePolarPlotData(tc)
            if is_octave()
                return % The `polarplot` function is not yet implemented in Octave. Consider using `polar`.
            end
            fig = figure("Visible","off");
            ezpolar("1+cos(theta)")

            p = plotlyfig(fig,"visible","off","treatAs",'ezpolar');

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(rmfield(p.data{1},["r" "theta"]), struct( ...
                "type", "scatterpolar", ...
                "subplot", "polar2", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.75, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testContourPlotData(tc)
            fig = figure("Visible","off");
            range = 0:0.1:3;
            [xVals,yVals] = meshgrid(range,range);
            zVals = sin(3*xVals).*cos(xVals+yVals);
            contour(xVals,yVals,zVals);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "type", "contour", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "name", '', ...
                "visible", true, ...
                "xtype", "array", ...
                "ytype", "array", ...
                "x", range, ...
                "y", range', ...
                "z", zVals, ...
                "autocontour", false, ...
                "contours", struct( ...
                    "end", 0.8, ...
                    "start", -0.8, ...
                    "size", 0.2, ...
                    "coloring", "lines", ...
                    "showlines", true ...
                ), ...
                "zauto", false, ...
                "zmin", -0.8, ...
                "zmax", 0.8, ...
                "showscale", false, ...
                "line", struct( ...
                    "width", 0.75, ...
                    "dash", "solid", ...
                    "color", "rgba(0,0,0,0)", ...
                    "smoothing", 0 ...
                ), ...
                "showlegend", false ...
            );
            if is_octave()
                expected.contours.end = 0.81412281872963299;
                expected.contours.start = -0.99767975543523912;
                expected.contours.size = 0.18118025741648722;
                expected.zmin = -0.81649949801875188;
                expected.zmax = 0.81412281872963299;
                expected.line = struct( ...
                    "width", 0.75, ...
                    "color", "rgba(0,0,0,0)" ...
                );
            else
                expected.reversescale = false;
            end
            tc.verifyEqual(rmfield(p.data{1}, "colorscale"), expected, 'AbsTol', 1e-16);
            try close(); catch; end
        end

        function testFunctionContourPlotData(tc)
            if is_octave()
                return % The `fcontour` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            fcontour(@(x,y) sin(3*x).*cos(x+y),[0 3 0 3],Fill="on",LineColor="k");
            chartTitle = "f(x,y) = sin(3*x)*cos(x+y)";
            title(chartTitle);
            colormap("spring");

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(rmfield(p.data{1}, ["colorscale" "x" "y" "z"]), struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "name", '{sin}({3} {x}) {cos}({x}+{y})', ...
                "type", "contour", ...
                "visible", true, ...
                "xtype", "array", ...
                "ytype", "array", ...
                "autocontour", false, ...
                "contours", struct( ...
                    "end", 0.8, ...
                    "start", -1, ...
                    "size", 0.2, ...
                    "coloring", "fill" ...
                ), ...
                "zauto", false, ...
                "zmin", -1, ...
                "zmax", 0.8, ...
                "showscale", false, ...
                "reversescale", false, ...
                "line", struct( ...
                    "width", 0.5, ...
                    "dash", "solid", ...
                    "color", "rgb(0,0,0)", ...
                    "smoothing", 0 ...
                ), ...
                "showlegend", true ...
            ), 'AbsTol', 1e-2);
            try close(); catch; end
        end

        function testContourfPlotData(tc)
            % contourf produces a filled contour trace.
            fig = figure("Visible","off");
            [x, y, z] = peaks(30);
            contourf(x, y, z, 10);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "type", "contour", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "name", '', ...
                "visible", true, ...
                "xtype", "array", ...
                "ytype", "array", ...
                "x", x(1,:), ...
                "y", y(:,1), ...
                "z", z, ...
                "autocontour", false, ...
                "contours", struct( ...
                    "start", PlotlyTestCase.Any(), ...
                    "end", PlotlyTestCase.Any(), ...
                    "size", PlotlyTestCase.Any(), ...
                    "coloring", "fill", ...
                    "showlines", true ...
                ), ...
                "zauto", false, ...
                "zmin", PlotlyTestCase.Any(), ...
                "zmax", PlotlyTestCase.Any(), ...
                "showscale", false, ...
                "colorscale", PlotlyTestCase.Any(), ...
                "line", struct( ...
                    "width", PlotlyTestCase.Any(), ...
                    "color", "rgb(217,217,217)", ...
                    "dash", PlotlyTestCase.Any(), ...
                    "smoothing", PlotlyTestCase.Any() ...
                ), ...
                "showlegend", false, ...
                "reversescale", false ...
            );
            if is_octave()
                % Octave's contour handler emits a simpler line
                % struct and no reversescale
                expected.line = rmfield(expected.line, {'dash', 'smoothing'});
                expected.line.color = "rgb(0,0,0)";
                expected = rmfield(expected, 'reversescale');
            end
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            if is_octave()
                tc.verifyEqual(size(p.data{1}.z), [30 30]);
            end
            try close(); catch; end
        end

        function testHeatmapData(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure(Visible="off");
            data = magic(5);
            heatmap(data);

            p = plotlyfig(fig,"visible","off");

            flipped = flip(data);
            nestZ = cellfun(@num2cell,num2cell(flipped,2),un=0)';

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(rmfield(p.data{1}, "colorscale"), struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "heatmap", ...
                "x", {num2cell(num2str((1:5)'))}, ...
                "y", {num2cell(num2str(flip(1:5)'))}, ...
                "z", {nestZ}, ...
                "zmin", min(data,[],"all"), ...
                "zmax", max(data,[],"all"), ...
                "connectgaps", false, ...
                "hoverongaps", false, ...
                "hoverinfo", "text", ...
                "text", {nestZ}, ...
                "hoverlabel", struct( ...
                    "bgcolor", "white" ...
                ), ...
                "showscale", true, ...
                "colorbar", struct( ...
                    "x", fig.Children.Position(1) + fig.Children.Position(3), ...
                    "y", fig.Children.Position(2), ...
                    "xanchor", "left", ...
                    "yanchor", "bottom", ...
                    "thicknessmode", "fraction", ...
                    "thickness", fig.Children.Position(3)/10, ...
                    "lenmode", "fraction", ...
                    "len", fig.Children.Position(4), ...
                    "ypad", 0, ...
                    "xpad", 10, ...
                    "outlinecolor", "rgb(150,150,150)" ...
                ), ...
                "visible", true, ...
                "opacity", 0.9500, ...
                "showlegend", false, ...
                "name", "" ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testHeatmap1x1Data(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure(Visible="off");
            heatmap(42);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data,1);
            d = p.data{1};
            tc.verifyEqual(d.type,"heatmap");

            % z and text must be nested cell arrays so they serialize
            % as 2D JSON arrays ([[42]]), not bare scalars (42).
            tc.verifyEqual(d.z,{{42}});
            tc.verifyEqual(d.text,{{42}});

            % x and y must be cell arrays so they serialize as JSON
            % arrays, not bare values.
            tc.verifyEqual(d.x,{{'1'}});
            tc.verifyEqual(d.y,{{'1'}});
            try close(); catch; end
        end

        function testHeatmap1x2Data(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure(Visible="off");
            heatmap(["x1" "x2"], "y1", [1.5 3.7], ...
                "GridVisible", true, ColorbarVisible=true, ...
                CellLabelFormat="%.2f");

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data,1);
            d = p.data{1};

            % z and text must be nested cell arrays so they serialize
            % as 2D JSON arrays ([[1.5, 3.7]])
            tc.verifyEqual(d.z,{{1.5, 3.7}});
            tc.verifyEqual(d.text,{{1.5, 3.7}});

            tc.verifyEqual(d.x,{'x1'; 'x2'});
            tc.verifyEqual(d.y,{{'y1'}});
            try close(); catch; end
        end

        function testHeatmap2x1Data(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure(Visible="off");
            heatmap("x1", ["y1"; "y2"], [1.5; -0.8], ...
                GridVisible=false, ColorbarVisible=false);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data,1);
            d = p.data{1};

            % z and text must be nested cell arrays so they serialize
            % as 2D JSON arrays ([[1.5]; [-0.8]])
            tc.verifyEqual(d.z,{{-0.8}, {1.5}});
            tc.verifyEqual(d.text,{{-0.8}, {1.5}});

            tc.verifyEqual(d.x,{{'x1'}});
            tc.verifyEqual(d.y,{'y2'; 'y1'});
            try close(); catch; end
        end

        function testHeatmapDataColorLimitsOverride(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            data = magic(5);
            zmin = -5;
            zmax = 5;
            h = heatmap(data);
            h.ColorLimits = [zmin, zmax];

            p = plotlyfig(fig,"visible","off");

            tc.verifyEqual(p.data{1}.zmin, zmin);
            tc.verifyEqual(p.data{1}.zmax, zmax);
            try close(); catch; end
        end

        function testTiledLayoutHeatmap(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            data = [1 2; 3 4];
            tiledlayout(2,2);
            for i = 1:4
                nexttile;
                heatmap(data);
            end

            p = plotlyfig(fig,"visible","off");

            flipped = flip(data);
            nestZ = cellfun(@num2cell,num2cell(flipped,2),un=0)';

            tc.verifyNumElements(p.data, 4);
            tc.verifyEqual(rmfield(p.data{1}, ["colorscale" "colorbar"]), struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "heatmap", ...
                "x", {num2cell(num2str((1:2)'))}, ...
                "y", {num2cell(num2str(flip(1:2)'))}, ...
                "z", {nestZ}, ...
                "zmin", min(data,[],"all"), ...
                "zmax", max(data,[],"all"), ...
                "connectgaps", false, ...
                "hoverongaps", false, ...
                "hoverinfo", "text", ...
                "text", {nestZ}, ...
                "hoverlabel", struct( ...
                    "bgcolor", "white" ...
                ), ...
                "showscale", true, ...
                "visible", true, ...
                "opacity", 0.9500, ...
                "showlegend", false, ...
                "name", "" ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqual(rmfield(p.data{1}.colorbar, ["thickness" "x"]), struct( ...
                "y", fig.Children.Children(4).Position(2), ...
                "xanchor", "left", ...
                "yanchor", "bottom", ...
                "thicknessmode", "fraction", ...
                "lenmode", "fraction", ...
                "len", fig.Children.Children(4).Position(4), ...
                "ypad", 0, ...
                "xpad", 10, ...
                "outlinecolor", "rgb(150,150,150)" ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testHeatmapTextColorBrightCells(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            data = [1 2; 3 4];
            h = heatmap(data);
            h.Colormap = repmat([0.9 0.9 0.9], 64, 1); % Light gray colormap

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.layout.annotations, numel(data));
            % All cells should have black text due to bright background
            for i = 1:numel(p.layout.annotations)
                ann = p.layout.annotations{i};
                tc.verifyEqual(ann.font.color, "rgb(0,0,0)"); % Black text
            end
            try close(); catch; end
        end

        function testHeatmapTextColorDarkCells(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            data = [1 2; 3 4];
            h = heatmap(data);
            h.Colormap = repmat([0.1 0.1 0.1], 64, 1); % Dark gray colormap

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.layout.annotations, numel(data));
            % All cells should have white text due to dark background
            for i = 1:numel(p.layout.annotations)
                ann = p.layout.annotations{i};
                tc.verifyEqual(ann.font.color, "rgb(255,255,255)"); % White text
            end
            try close(); catch; end
        end

        function testHeatmapMixedColorCells(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("visible","off");
            data = [ ...
                4.316 3.895 3.176 2.850 2.667 2.429 2.173 1.920;
                4.226 3.847 3.179 2.863 2.688 2.455 2.203 1.954;
                3.951 3.650 3.113 2.824 2.666 2.458 2.224 1.998;
                3.820 3.556 3.091 2.828 2.684 2.495 2.271 2.060;
                3.701 3.459 3.036 2.787 2.650 2.475 2.260 2.062;
                3.490 3.289 2.937 2.706 2.580 2.421 2.227 2.048;
                3.292 3.128 2.820 2.608 2.493 2.353 2.186 2.031;
                3.073 2.939 2.675 2.481 2.377 2.259 2.121 1.992;
            ];
            h = heatmap(data);
            nColors = 256;
            zeroPos = round(0.5 * (nColors-1)) + 1;
            redToWhite = [linspace(1,1,zeroPos)', linspace(0,1,zeroPos)', linspace(0,1,zeroPos)'];
            whiteToGreen = [linspace(1,0,nColors-zeroPos+1)', ...
                            linspace(1,1,nColors-zeroPos+1)', ...
                            linspace(1,0,nColors-zeroPos+1)'];
            customMap = [redToWhite; whiteToGreen(2:end,:)];
            colormap(h, customMap);
            caxis([min(data(:)) max(data(:))]);

            p = plotlyfig(fig,"visible","off");

            isWhite = cellfun(@(ann) ann.font.color == "rgb(255,255,255)", p.layout.annotations);
            positions = cellfun(@(ann) ann.x + "," + ann.y, p.layout.annotations);
            actual = positions(isWhite);
            expected = ["5,0" "6,0" "6,1" "6,2" "6,3" "6,4" "6,5" "6,6" "6,7" ...
                    "7,0" "7,1" "7,2" "7,3" "7,4" "7,5" "7,6" "7,7"];
            tc.verifyEqual(actual, expected);
            try close(); catch; end
        end

        function testHeatmapCellTextAnnotations(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            data = [1 2; 3 4; 5 6];
            heatmap(data);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.layout.annotations, numel(data));
            actualStrings = cellfun(@(ann) ann.text, p.layout.annotations, 'UniformOutput', false);
            expectedStrings = arrayfun(@(v) string(v), data(:));
            tc.verifyEqual(sort(actualStrings(:)), sort(expectedStrings(:)));
            try close(); catch; end
        end

        function testHeatmapTitleAnnotation(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            data = [1 2; 3 4];
            titleString = "title";
            heatmap(data);
            title(titleString);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.layout.annotations, numel(data)+1);
            actualStrings = string(cellfun(@(ann) ann.text, p.layout.annotations, 'UniformOutput', false));
            tc.verifyTrue(any(contains(actualStrings, titleString)));
            try close(); catch; end
        end

        function testHeatmapAxisLabels(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            data = [1 2; 3 4];
            xLabelText = "X Axis Label";
            yLabelText = "Y Axis Label";
            heatmap(data);
            xlabel(xLabelText);
            ylabel(yLabelText);

            p = plotlyfig(fig,"visible","off");

            tc.verifyEqual(p.layout.xaxis1.title.text, xLabelText);
            tc.verifyEqual(p.layout.yaxis1.title.text, yLabelText);
            try close(); catch; end
        end

        function testHeatmapWithNaNValues(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            data = [1 2 NaN; 4 NaN 6; 7 8 9];
            heatmap(data);

            p = plotlyfig(fig,"visible","off");

            flipped = flip(data);
            nestZ = cellfun(@num2cell,num2cell(flipped,2),un=0)';

            tc.verifyNumElements(p.data, 1);
            heatmapData = p.data{1};
            tc.verifyEqual(heatmapData.z, nestZ);
            try close(); catch; end
        end

        function testHeatmapAllNaNValues(tc)
            if is_octave()
                return % The `heatmap` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            data = [NaN NaN; NaN NaN];
            heatmap(data);

            p = plotlyfig(fig,"visible","off");

            flipped = flip(data);
            nestZ = cellfun(@num2cell,num2cell(flipped,2),un=0)';

            tc.verifyNumElements(p.data, 1);
            heatmapData = p.data{1};
            tc.verifyEqual(heatmapData.z, nestZ);
            tc.verifyTrue(all(cellfun(@(row) all(cellfun(@isnan,row)), heatmapData.z)));
            tc.verifyTrue(all(cellfun(@(row) all(cellfun(@isnan,row)), heatmapData.text)));
            try close(); catch; end
        end

        function testPColorHeatmapData(tc)
            % pcolor must convert to a 2D heatmap: one z value per
            % cell, x/y at the cell centers.
            fig = figure("Visible","off");
            [X, Y] = meshgrid(1:4, 1:3);
            C = [1 2 3 4; 5 6 7 8; 9 10 11 12];
            pcolor(X, Y, C);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(p.data{1}.type, "heatmap");
            tc.verifyEqual(p.data{1}.z, C(1:end-1, 1:end-1));
            tc.verifyEqual(p.data{1}.x, mean([X(1,1:end-1); X(1,2:end)]));
            tc.verifyEqual(p.data{1}.y, mean([Y(1:end-1,1)'; Y(2:end,1)']));
            tc.verifyFalse(p.data{1}.showscale);
            try close(); catch; end
        end

        function testRoseBarpolarData(tc)
            % rose petals must convert to barpolar bars (one bar per
            % petal) instead of a polar line loop, so each petal hovers
            % as one unit.
            fig = figure("Visible","off");
            angles = deg2rad(0:30:330);
            rose(angles);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(p.data{1}.type, "barpolar");
            tc.verifyEqual(p.data{1}.marker.color, PlotlyTestCase.AnyColorString());
            tc.verifyEqual(p.data{1}.marker.line.color, PlotlyTestCase.AnyColorString());
            tc.verifyGreaterThanOrEqual(p.data{1}.marker.line.width, 1);
            tc.verifyEqual(numel(p.data{1}.theta), numel(p.data{1}.r));
            tc.verifyEqual(sum(p.data{1}.r), numel(angles));
            try close(); catch; end
        end

        function testImagePlotData(tc)
            % image() becomes a heatmap trace.
            fig = figure("Visible","off");
            n = 8;
            z = rand(n, n)*255;
            image(z);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "heatmap", ...
                "x", 1:n, ...
                "y", 1:n, ...
                "z", z, ...
                "name", '', ...
                "opacity", 1, ...
                "visible", true, ...
                "showscale", false, ...
                "zauto", false, ...
                "zmin", 0, ...
                "zmax", 255, ...
                "colorscale", PlotlyTestCase.Any(), ...
                "showlegend", false ...
            );
            if ~is_octave()
                % MATLAB's image CLim auto-ranges over the data
                % instead of starting at 0
                expected.zmin = get(gca, 'CLim');
                expected.zmin = expected.zmin(1);
            end
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            if is_octave()
                % image data is stored with y reversed (top row first)
                tc.verifyEqual(p.layout.yaxis1.range, [8.5 0.5]);
            end
            try close(); catch; end
        end

        function testImagescPlotData(tc)
            % imagesc() becomes a heatmap trace.
            fig = figure("Visible","off");
            n = 8;
            z = rand(n, n);
            imagesc(z);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "heatmap", ...
                "x", 1:n, ...
                "y", 1:n, ...
                "z", z, ...
                "name", '', ...
                "opacity", 1, ...
                "visible", true, ...
                "showscale", false, ...
                "zauto", false, ...
                "zmin", PlotlyTestCase.Any(), ...
                "zmax", PlotlyTestCase.Any(), ...
                "colorscale", PlotlyTestCase.Any(), ...
                "showlegend", false ...
            );
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            if is_octave()
                tc.verifyEqual(p.layout.yaxis1.range, [8.5 0.5]);
            end
            try close(); catch; end
        end

        function testPatchPlotData(tc)
            fig = figure("Visible","off");
            x = [0 1 1 0];
            y = [0 0 1 1];
            patch(x, y, "red");

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", 'scatter', ...
                "x", [x x(1)], ...
                "y", [y y(1)], ...
                "name", '', ...
                "visible", true, ...
                "fill", 'tozeroy', ...
                "mode", 'lines', ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "sizeref", 1, ...
                    "sizemode", "diameter", ...
                    "size", 6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "fillcolor", "rgba(255,0,0,1.000000)", ...
                "showlegend", false ...
            ));
            try close(); catch; end
        end

        function testFillPlotData(tc)
            fig = figure("Visible","off");
            x1 = [1 2 3 4 5];
            y1 = [1 2 1 2 1];
            x2 = [1 2 3 4 5];
            y2 = [2 3 2 3 2];
            fill(x1, y1, 'blue', x2, y2, 'green');

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 2);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", 'scatter', ...
                "x", [x1 x1(1)], ...
                "y", [y1 y1(1)], ...
                "name", '', ...
                "visible", true, ...
                "fill", 'tozeroy', ...
                "mode", 'lines', ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "sizeref", 1, ...
                    "sizemode", "diameter", ...
                    "size", 6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "fillcolor", "rgba(0,0,255,1.000000)", ...
                "showlegend", false ...
            ));
            tc.verifyEqualStructs(p.data{2}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", 'scatter', ...
                "x", [x2 x2(1)], ...
                "y", [y2 y2(1)], ...
                "name", '', ...
                "visible", true, ...
                "fill", 'tozeroy', ...
                "mode", 'lines', ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "sizeref", 1, ...
                    "sizemode", "diameter", ...
                    "size", 6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "fillcolor", "rgba(0,255,0,1.000000)", ...
                "showlegend", false ...
            ));
            try close(); catch; end
        end

        function testRectanglePlotData(tc)
            % rectangle() becomes a single closed-loop lines trace.
            fig = figure("Visible","off");
            x = [0 0 2 2 0];
            y = [0 3 3 0 0];
            rectangle("Position", [0 0 2 3], "FaceColor", "r");

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "x", x, ...
                "y", y, ...
                "name", '', ...
                "mode", 'lines', ...
                "visible", true, ...
                "fill", "tonexty", ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "fillcolor", PlotlyTestCase.AnyColorString(), ...
                "showlegend", false ...
            );
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            try close(); catch; end
        end
    end
end
