classdef Test_plotlyfig_lines < PlotlyTestCase
    methods
        function testLinePlotData(tc)
            fig = figure("Visible","off");
            y = [0.0301 0.4411 0.7007 0.7030 0.5102 0.6122 0.7464 0.8014 0.3367 0.5641];
            x = 1:10;
            plot(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "x", x, ...
                "y", y, ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testLinePlotDatetimeXaxis(tc)
            if is_octave()
                return % Octave does not support plotting datetime data.
            end
            fig = figure("Visible","off");
            y = [0.0301 0.4411 0.7007 0.7030 0.5102 0.6122 0.7464 0.8014 0.3367 0.5641];
            x = datetime(2025,1:10,1);
            plot(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}.x, convertDate(x));
            try close(); catch; end
        end

        function testLinePlotLayout(tc)
            fig = figure("Visible","off");
            y = [0.0301 0.4411 0.7007 0.7030 0.5102 0.6122 0.7464 0.8014 0.3367 0.5641];
            x = 1:10;
            plot(x,y);

            p = plotlyfig(fig,"visible","off");

            if is_octave()
                family = "Open Sans, sans-serif";
            else
                family = "Arial, sans-serif";
            end

            expected = struct( ...
                "autosize", false, ...
                "margin", struct( ...
                    "pad", 0, ...
                    "l", 0, ...
                    "r", 0, ...
                    "b", 0, ...
                    "t", 0 ...
                ), ...
                "showlegend", false, ...
                "width", PlotlyTestCase.AnyNumber(true), ...
                "height", PlotlyTestCase.AnyNumber(true), ...
                "paper_bgcolor", PlotlyTestCase.AnyColorString(), ...
                "plot_bgcolor", PlotlyTestCase.AnyColorString(), ...
                "hovermode", 'closest', ...
                "xaxis1", struct( ...
                    "side", 'bottom', ...
                    "zeroline", false, ...
                    "autorange", false, ...
                    "linecolor", PlotlyTestCase.AnyColorString(), ...
                    "linewidth", 1, ...
                    "exponentformat", 'none', ...
                    "tickfont", struct( ...
                        "size", 10, ...
                        "family", family, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "ticklen", PlotlyTestCase.AnyNumber(), ...
                    "tickcolor", PlotlyTestCase.AnyColorString(), ...
                    "tickwidth", 1, ...
                    "tickangle", 0, ...
                    "ticks", "inside", ...
                    "showgrid", false, ...
                    "gridcolor", PlotlyTestCase.AnyColorString(), ...
                    "type", 'linear', ...
                    "showticklabels", true, ...
                    "tickmode", "array", ...
                    "tickvals", [1 2 3 4 5 6 7 8 9 10], ...
                    "range", [1 10], ...
                    "mirror", "ticks", ...
                    "ticktext", {{'1'; '2'; '3'; '4'; '5'; '6'; '7'; '8'; '9'; '10'}}, ...
                    "titlefont", struct( ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "family", family, ...
                        "size", 11 ...
                    ), ...
                    "showline", true, ...
                    "domain", [0.13 0.905], ...
                    "anchor", "y1" ...
                ), ...
                "scene1", struct( ...
                    "domain", struct( ...
                        "x", [0.13 0.905], ...
                        "y", [0.11 0.925] ...
                    ) ...
                ), ...
                "yaxis1", struct( ...
                    "side", 'left', ...
                    "zeroline", false, ...
                    "autorange", false, ...
                    "linecolor", PlotlyTestCase.AnyColorString(), ...
                    "linewidth", 1, ...
                    "exponentformat", 'none', ...
                    "tickfont", struct( ...
                        "size", 10, ...
                        "family", family, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "ticklen", PlotlyTestCase.AnyNumber(), ...
                    "tickcolor", PlotlyTestCase.AnyColorString(), ...
                    "tickwidth", 1, ...
                    "tickangle", 0, ...
                    "ticks", "inside", ...
                    "showgrid", false, ...
                    "gridcolor", PlotlyTestCase.AnyColorString(), ...
                    "type", 'linear', ...
                    "showticklabels", true, ...
                    "tickmode", "array", ...
                    "tickvals", [0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9], ...
                    "range", [0 0.9], ...
                    "mirror", "ticks", ...
                    "ticktext", {{'0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'}}, ...
                    "titlefont", struct( ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "family", family, ...
                        "size", 11 ...
                    ), ...
                    "showline", true, ...
                    "domain", [0.11 0.925], ...
                    "anchor", "x1" ...
                ), ...
                "annotations", {{struct( ...
                    "showarrow", false, ...
                    "xref", "paper", ...
                    "yref", "paper", ...
                    "xanchor", 'center', ...
                    "align", 'center', ...
                    "yanchor", "bottom", ...
                    "text", "<b><b></b></b>", ...
                    "x", 0.5175, ...
                    "y", 0.935, ...
                    "font", struct( ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "family", family, ...
                        "size", 11 ...
                    ), ...
                    "bordercolor", "rgba(0,0,0,0)", ...
                    "textangle", 0, ...
                    "borderwidth", 0.5, ...
                    "borderpad", 3 ...
                )}} ...
            );
            if is_octave()
                expected.xaxis1.tickvals = [0 2 4 6 8 10];
                expected.xaxis1.range = [0 10];
                expected.xaxis1.ticktext = {'0'; '2'; '4'; '6'; '8'; '10'};
                expected.yaxis1.tickvals = [0 0.2 0.4 0.6 0.8 1];
                expected.yaxis1.range = [0 1];
                expected.yaxis1.ticktext = {'0'; '0.2'; '0.4'; '0.6'; '0.8'; '1'};
            end
            tc.verifyEqualStructs(p.layout, expected, 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testAreaPlotData(tc)
            fig = figure("Visible","off");
            y = [0.6297 0.9559 0.7551 0.5261 0.8501 0.8160 0.1321 0.7607 0.6172 0.3976];
            x = 1:10;
            area(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "scatter", ...
                "x", x, ...
                "y", y, ...
                "name", '', ...
                "visible", true, ...
                "fill", "tozeroy", ...
                "mode", "lines", ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "fillcolor", PlotlyTestCase.AnyColorString(), ...
                "showlegend", true ...
            );
            if is_octave()
                expected.x = PlotlyTestCase.Any();
                expected.y = PlotlyTestCase.Any();
                expected.marker = PlotlyTestCase.Any();
                expected.showlegend = false;
            end
            tc.verifyEqualStructs(p.data{1}, expected);
            try close(); catch; end
        end

        function testScatterPlotData(tc)
            fig = figure("Visible","off");
            x = linspace(0,3*pi,200);
            y = cos(x) + rand(1,200);
            scatter(x,y);

            p = plotlyfig(fig,"visible","off");

            if is_octave()
                xData = x(:);
                yData = y(:);
            else
                xData = x;
                yData = y;
            end

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "mode", "markers", ...
                "visible", true, ...
                "name", '', ...
                "x", xData, ...
                "y", yData, ...
                "marker", struct( ...
                    "sizeref", 1, ...
                    "sizemode", "area", ...
                    "size", 36 * ones(size(xData)), ...
                    "line", struct( ...
                        "width", 0.7500, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "symbol", "circle", ...
                    "color", "rgba(0,0,0,0)", ...
                    "opacity", 1 ...
                ), ...
                "showlegend", false ...
            ));
            try close(); catch; end
        end

        function testSingleScatterPlotData(tc)
            fig = figure("Visible","off");
            x = 1;
            y = 1;
            scatter(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "mode", "markers", ...
                "visible", true, ...
                "name", '', ...
                "x", {{x}}, ...
                "y", {{y}}, ...
                "marker", struct( ...
                    "sizeref", 1, ...
                    "sizemode", "area", ...
                    "size", {{36}}, ...
                    "line", struct( ...
                        "width", 0.7500, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "symbol", "circle", ...
                    "color", "rgba(0,0,0,0)", ...
                    "opacity", 1 ...
                ), ...
                "showlegend", false ...
            );
            if ~is_octave()
                expected.hoverinfo = PlotlyTestCase.Any();
                expected.hovertext = PlotlyTestCase.Any();
            end
            tc.verifyEqualStructs(p.data{1}, expected);
            try close(); catch; end
        end

        function testSingleDatetimeScatterPlotData(tc)
            if is_octave()
                return % Octave does not support plotting datetime data.
            end
            fig = figure("Visible","off");
            x = 1;
            y = datetime("today");
            scatter(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(p.data{1}.y, {convertDate(y)});
            try close(); catch; end
        end

        function testMultiDateScatterData(tc)
            % multiple datetimes on the y axis: convertDate yields a
            % char matrix, kept as-is (renders as an array of date
            % strings)
            if is_octave()
                return % Octave does not support plotting datetime data.
            end
            fig = figure("Visible","off");
            x = 1:5;
            y = datetime(2026,8,1:5);
            scatter(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(p.data{1}.y, convertDate(y));
            tc.verifyEqual(p.layout.yaxis1.type, "date");
            try close(); catch; end
        end

        function testLogLogPlot(tc)
            fig = figure("Visible","off");
            zeta = 0.5; % damping factor
            color = "r";
            w = logspace(-1, 1, 1000); % values equally spaced logarithmically
            a = w.^2 - 1;
            b = 2*w*zeta;
            gain = sqrt(1./(a.^2 + b.^2));
            loglog(w, gain, color=color);
            axis([0.1 10 0.01 100]);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(p.data{1}, struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "name", '', ...
                "mode", 'lines', ...
                "x", w, ...
                "y", gain, ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", "rgb(255,0,0)" ...
                ), ...
                "line", struct( ...
                    "color", "rgb(255,0,0)", ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "visible", true, ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testStairsPlotData(tc)
            fig = figure("Visible","off");
            x = 2:2:8;
            y = [1 1 2 2];
            stairs(x,y,'-or')

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines+markers', ...
                "line", struct( ...
                    "color", "rgb(255,0,0)", ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", PlotlyTestCase.AnyNumber(), ...
                    "symbol", "circle", ...
                    "line", struct( ...
                        "width", 0.5, ...
                        "color", "rgb(255,0,0)" ...
                    ), ...
                    "color", "rgba(0,0,0,0)" ...
                ), ...
                "showlegend", false ...
            );
            if is_octave()
                expected.x = [2 4 4 6 6 8 8];
                expected.y = [1 1 1 1 2 2 2];
            else
                expected.x = x;
                expected.y = y;
            end
            if ~is_octave()
                expected.line.shape = "hv";
            end
            tc.verifyEqual(p.data{1}, expected, 'AbsTol', 1e-4);
            try close(); catch; end
        end

        function testPlotmatrixData(tc)
            fig = figure("Visible","off");
            columns = [ ...
                0.67  0.77  0.42;
                0.43  0.70  0.66;
                0.45  0.13  0.72;
                0.61  0.13  0.53;
                0.06  0.09  0.11;
                0.32  0.01  0.63];
            plotmatrix(columns);

            p = plotlyfig(fig,"visible","off");

            if is_octave()
                tc.verifyNumElements(p.data, 9); % 3x3 matrix, no parent plot
                for i = 1:9
                    d = p.data{i};
                    tc.verifyEqual(d.xaxis, sprintf("x%d", i));
                    tc.verifyEqual(d.yaxis, sprintf("y%d", i));
                    if ismember(i, [1 5 9])
                        tc.verifyEqual(d.type, "bar");
                    else
                        tc.verifyEqual(d.type, "scatter");
                        tc.verifyEqual(d.mode, "markers");
                    end
                end
                try close(); catch; end
                return
            end

            % MATLAB: 9 traces with no parent plot; the 6 off-diagonal
            % scatters come first, then the 3 diagonal histograms as bars
            tc.verifyNumElements(p.data, 9);
            scatterXY = { ...
                [0.77 0.7 0.13 0.13 0.09 0.01], [0.42 0.66 0.72 0.53 0.11 0.63]; ...
                [0.67 0.43 0.45 0.61 0.06 0.32], [0.42 0.66 0.72 0.53 0.11 0.63]; ...
                [0.42 0.66 0.72 0.53 0.11 0.63], [0.77 0.7 0.13 0.13 0.09 0.01]; ...
                [0.67 0.43 0.45 0.61 0.06 0.32], [0.77 0.7 0.13 0.13 0.09 0.01]; ...
                [0.42 0.66 0.72 0.53 0.11 0.63], [0.67 0.43 0.45 0.61 0.06 0.32]; ...
                [0.77 0.7 0.13 0.13 0.09 0.01], [0.67 0.43 0.45 0.61 0.06 0.32] ...
            };
            for i = 1:6
                tc.verifyEqualStructs(p.data{i}, struct( ...
                    "type", "scatter", ...
                    "xaxis", sprintf("x%d", i), ...
                    "yaxis", sprintf("y%d", i), ...
                    "visible", true, ...
                    "name", '', ...
                    "mode", 'markers', ...
                    "x", scatterXY{i,1}, ...
                    "y", scatterXY{i,2}, ...
                    "line", struct(), ...
                    "marker", struct( ...
                        "size", 3, ...
                        "symbol", "circle", ...
                        "maxdisplayed", 7, ...
                        "line", struct( ...
                            "width", 0.5 ...
                        ), ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "showlegend", false ...
                ), 'AbsTol', 1e-15);
            end
            barY = {[2 4]; [4 2]; [4 2]};
            for i = 1:3
                tc.verifyEqualStructs(p.data{i+6}, struct( ...
                    "xaxis", sprintf("x%d", i+6), ...
                    "yaxis", sprintf("y%d", i+6), ...
                    "type", "bar", ...
                    "x", [0.25 0.75], ...
                    "width", [0.5 0.5], ...
                    "y", barY{i}, ...
                    "marker", struct( ...
                        "line", struct( ...
                            "color", PlotlyTestCase.AnyColorString() ...
                        ), ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "opacity", 0.75, ...
                    "name", '', ...
                    "visible", true, ...
                    "showlegend", true ...
                ), 'AbsTol', 1e-15);
            end
            try close(); catch; end
        end

        function testStemPlotData(tc)
            fig = figure("Visible","off");
            x = 1:10;
            y = rand(10,1);
            stem(x, y, 'filled');

            p = plotlyfig(fig,"visible","off");

            if is_octave()
                % Octave's stem handler renders the y=0 baseline as a
                % second trace and uses LineWidth 0.5 with row vectors
                tc.verifyNumElements(p.data, 2);
                lineWidth = 0.5;
                xData = reshape([x; x; nan(1,length(x))], 1, []);
                yData = reshape([zeros(1,length(y)); y'; nan(1,length(y))], 1, []);
                colors = repmat({"rgba(0,0,0,0)" PlotlyTestCase.AnyColorString() "rgba(0,0,0,0)"},1,10);
            else
                tc.verifyNumElements(p.data, 1);
                lineWidth = 1;
                xData = reshape([x; x; nan(1,length(x))], [], 1);
                yData = reshape([zeros(1,length(y)); y'; nan(1,length(y))], [], 1);
                colors = repmat({"rgba(0,0,0,0)" PlotlyTestCase.AnyColorString() "rgba(0,0,0,0)"},1,10)';
            end
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "scatter", ...
                "visible", true, ...
                "name", '', ...
                "mode", "lines+markers", ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", lineWidth, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "symbol", "circle", ...
                    "line", struct( ...
                        "width", lineWidth, ...
                        "color", {colors} ...
                    ), ...
                    "color", {colors} ...
                ), ...
                "x", xData, ...
                "y", yData, ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testErrorbarData(tc)
            fig = figure("Visible","off");
            x = 1:10;
            y = rand(1,10);
            err = 0.1*ones(1,10);
            errorbar(x,y,err);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false, ...
                "error_y", struct( ...
                    "visible", true, ...
                    "type", "data", ...
                    "symmetric", false, ...
                    "thickness", 0.5, ...
                    "width", 6, ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ) ...
            );
            if is_octave()
                expected.x = x(:);
                expected.y = y(:);
                expected.error_y.array = err(:);
                expected.error_y.arrayminus = err(:);
            else
                expected.x = x;
                expected.y = y;
                expected.error_y.array = err;
                expected.error_y.arrayminus = err;
            end
            if ~is_octave()
                expected.error_x = struct( ...
                    "visible", true, ...
                    "type", "data", ...
                    "array", zeros(1,0), ...
                    "arrayminus", zeros(1,0), ...
                    "thickness", 0.5, ...
                    "width", 6, ...
                    "color", PlotlyTestCase.AnyColorString() ...
                );
            end
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testDoubleYAxisLinePlotData(tc)
            if is_octave()
                return % The `yyaxis` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            x = linspace(0,10);
            y = sin(3*x);
            yyaxis left
            plot(x,y);
            y2 = sin(3*x).*exp(0.5*x);
            yyaxis right
            plot(x,y2);
            ylim([-150 150]);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 4);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "x", x, ...
                "y", y, ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqualStructs(p.data{2}, struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y2", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "x", x, ...
                "y", y2, ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testDoubleYAxisLineLegend(tc)
            if is_octave()
                return % The `yyaxis` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            t = (1:10)';
            y1 = randn(10,1);
            y2 = randn(10,1);
            yyaxis left;
            plot(t,y1);
            yyaxis right
            plot(t,y2)
            legend(["y1_legend" "y2_legend"])

            p = plotlyfig(fig,"visible","off");

            tc.verifyEqual(p.data{1}.name, 'y1_legend');
            tc.verifyEqual(p.data{1}.showlegend, true);
            tc.verifyEqual(p.data{1}.legendrank, 1);
            tc.verifyEqual(p.data{2}.name, 'y2_legend');
            tc.verifyEqual(p.data{2}.showlegend, true);
            tc.verifyEqual(p.data{2}.legendrank, 2);
            try close(); catch; end
        end

        function testVerticalConstantLinePlotData(tc)
            if is_octave()
                return; % xline not supported in Octave.
            end
            fig = figure("Visible","off");
            xline(1);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "scatter", ...
                "visible", true, ...
                "x", [1 1], ...
                "y", [0 1], ...
                "name", '', ...
                "mode", "lines", ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "showlegend", true ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testVerticalConstantLineWithLabel(tc)
            if is_octave()
                return; % xline not supported in Octave.
            end
            fig = figure("Visible","off");
            label = "label";
            alignment = "left";
            width = 3;
            xl = xline(1,'r--',label,LineWidth=width);
            xl.LabelHorizontalAlignment = alignment;

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(p.data{1}.line, struct( ...
                "color", "rgb(255,0,0)", ...
                "width", width, ...
                "dash", "dash" ...
            ));
            tc.verifyTrue(any(cellfun(@(ann) contains(ann.text,label), p.layout.annotations)));
            tc.verifyTrue(any(cellfun(@(ann) ann.xanchor == alignment, p.layout.annotations)));
            try close(); catch; end
        end

        function testStackedPlotData(tc)
            if is_octave()
                return % The `stackedplot` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            x = 1:5;
            a = cos(x);
            b = exp(x);
            dt = datetime(2010,1,1) + years(x);
            tb = table(dt',a',b',VariableNames=["date" "a" "b"]);
            stackedplot(tb);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3);
            expected1 = struct( ...
                "type", "scatter", ...
                "visible", true, ...
                "name", 'date', ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "x", x, ...
                "y", b', ...
                "mode", "lines", ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "showlegend", false ...
            );
            tc.verifyEqualStructs(p.data{1}, expected1);
            tc.verifyEqualStructs(p.data{2}, struct( ...
                "type", "scatter", ...
                "visible", true, ...
                "name", 'a', ...
                "xaxis", "x1", ...
                "yaxis", "y2", ...
                "x", x, ...
                "y", a', ...
                "mode", "lines", ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ) ...
            ));
            tc.verifyEqualStructs(p.data{3}, struct( ...
                "type", "scatter", ...
                "visible", true, ...
                "name", 'b', ...
                "xaxis", "x1", ...
                "yaxis", "y3", ...
                "x", x, ...
                "y", dt', ...
                "mode", "lines", ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ) ...
            ));
            try close(); catch; end
        end

        function testDoubleYAxisAreaPlotData(tc)
            if is_octave()
                return % The `yyaxis` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            x = linspace(0,10);
            y = sin(3*x);
            yyaxis left
            area(x,y);
            y2 = sin(3*x).*exp(0.5*x);
            yyaxis right
            area(x,y2);
            ylim([-150 150]);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 4);
            expected1 = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "scatter", ...
                "x", x, ...
                "y", y, ...
                "name", '', ...
                "visible", true, ...
                "fill", "tozeroy", ...
                "mode", "lines", ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "fillcolor", PlotlyTestCase.AnyColorString(), ...
                "showlegend", true ...
            );
            expected2 = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y2", ...
                "type", "scatter", ...
                "x", x, ...
                "y", y2, ...
                "name", '', ...
                "visible", true, ...
                "fill", "tozeroy", ...
                "mode", "lines", ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "fillcolor", PlotlyTestCase.AnyColorString(), ...
                "showlegend", true ...
            );
            tc.verifyEqualStructs(p.data{1}, expected1);
            tc.verifyEqualStructs(p.data{2}, expected2);
            try close(); catch; end
        end

        function testTitleFont(tc)
            fig = figure("Visible","off");
            x = 1:10;
            y = x;
            plot(x,y);
            title("Custom Title","FontSize",24,"Color","g","FontName","Arial");

            p = plotlyfig(fig,"visible","off");

            annotation = p.layout.annotations{1};
            tc.verifyEqual(annotation.text, "<b><b>Custom Title</b></b>");
            tc.verifyEqual(annotation.font, struct( ...
                "color", "rgb(0,255,0)", ...
                "family", "Arial, sans-serif", ...
                "size", 24 ...
            ));
            try close(); catch; end
        end

        function testAxisLabelSizeFont(tc)
            fig = figure("Visible","off");
            x = 1:10;
            y = x;
            plot(x,y);
            xlabel("X Label","FontSize",20,"Color","b", ...
                    "FontName","Comic Sans MS");
            ylabel("Y Label","FontSize",20,"Color","r", ...
                    "FontName","Comic Sans MS");

            p = plotlyfig(fig,"visible","off");

            tc.verifyEqual(p.layout.xaxis1.title, struct( ...
                'text', 'X Label' ...
            ));
            tc.verifyEqual(p.layout.xaxis1.titlefont, struct( ...
                'color', 'rgb(0,0,255)', ...
                'size', 20, ...
                'family', 'Droid Sans, sans-serif' ...
            ));
            tc.verifyEqual(p.layout.yaxis1.title, struct( ...
                'text', 'Y Label' ...
            ));
            tc.verifyEqual(p.layout.yaxis1.titlefont, struct( ...
                'color', 'rgb(255,0,0)', ...
                'size', 20, ...
                'family', 'Droid Sans, sans-serif' ...
            ));
            try close(); catch; end
        end

        function testPlotWithCustomDataTip(tc)
            if is_octave()
                return % DataTipTemplate is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            x = 1:5;
            y = [2 4 6 8 10];
            h = plot(x, y);
            customData = ["Alpha", "Beta", "Gamma", "Delta", "Epsilon"];
            h.DataTipTemplate.DataTipRows(end+1) = dataTipTextRow("Label", customData);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyTrue(isfield(p.data{1}, "hovertext"));
            tc.verifyTrue(isfield(p.data{1}, "hoverinfo"));
            tc.verifyEqual(p.data{1}.hoverinfo, "text");

            expectedHovertext = "X: " + string(x(:)) + "<br>" + "Y: " ...
                    + string(y(:)) + "<br>" + "Label: " + customData(:) + "<br>";
            tc.verifyEqual(p.data{1}.hovertext, expectedHovertext);
            try close(); catch; end
        end

        function testPlotTableDataTip(tc)
            if is_octave()
                return % DataTipTemplate is not yet implemented in Octave.
            end
            tb = table();
            tb.time = (2:2:12)';
            tb.Saved = rand(6,1);
            tb.Sim1 = rand(6,1);
            tb.Sim2 = rand(6,1);
            names = ["Saved" "Sim1" "Sim2"];
            fig = figure("Visible","off");
            plot(tb,"time",names);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3);
            tc.verifyTrue(isfield(p.data{1}, "hovertext"));
            tc.verifyTrue(isfield(p.data{1}, "hoverinfo"));
            tc.verifyEqual(p.data{1}.hoverinfo, "text");
            expectedHovertext = "time: " + string(tb.time) + "<br>" + ...
                                "Saved: " + string(tb.Saved) + "<br>";
            tc.verifyEqual(p.data{1}.hovertext, expectedHovertext);

            tc.verifyTrue(isfield(p.data{2}, "hovertext"));
            tc.verifyTrue(isfield(p.data{2}, "hoverinfo"));
            tc.verifyEqual(p.data{2}.hoverinfo, "text");
            expectedHovertext = "time: " + string(tb.time) + "<br>" + ...
                                "Sim1: " + string(tb.Sim1) + "<br>";
            tc.verifyEqual(p.data{2}.hovertext, expectedHovertext);

            tc.verifyTrue(isfield(p.data{3}, "hovertext"));
            tc.verifyTrue(isfield(p.data{3}, "hoverinfo"));
            tc.verifyEqual(p.data{3}.hoverinfo, "text");
            expectedHovertext = "time: " + string(tb.time) + "<br>" + ...
                                "Sim2: " + string(tb.Sim2) + "<br>";
            tc.verifyEqual(p.data{3}.hovertext, expectedHovertext);
            try close(); catch; end
        end

        function testPlotWithMultipleCustomDataTips(tc)
            if is_octave()
                return % DataTipTemplate is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            x = 1:3;
            y = [10 20 30];
            h = plot(x, y);
            names = ["A", "B", "C"];
            values = [100, 200, 300];
            h.DataTipTemplate.DataTipRows(end+1) = dataTipTextRow("Name", names);
            h.DataTipTemplate.DataTipRows(end+1) = dataTipTextRow("Value", values);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyTrue(isfield(p.data{1}, "hovertext"));
            tc.verifyEqual(p.data{1}.hoverinfo, "text");

            expectedHovertext = "X: " + string(x(:)) + "<br>" + "Y: " + string(y(:)) + "<br>" + ...
                "Name: " + names(:) + "<br>" + "Value: " + string(values(:)) + "<br>";
            tc.verifyEqual(p.data{1}.hovertext, expectedHovertext);
            try close(); catch; end
        end

        function testScatterWithCustomDataTip(tc)
            if is_octave()
                return % DataTipTemplate is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            x = [1 2 3];
            y = [4 5 6];
            h = scatter(x, y);
            labels = ["Point1", "Point2", "Point3"];
            h.DataTipTemplate.DataTipRows(end+1) = dataTipTextRow("ID", labels);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyTrue(isfield(p.data{1}, "hovertext"));
            tc.verifyEqual(p.data{1}.hoverinfo, "text");

            expectedHovertext = "X: " + string(x(:)) + "<br>" + "Y: " ...
                    + string(y(:)) + "<br>" + "ID: " + labels(:) + "<br>";
            tc.verifyEqual(p.data{1}.hovertext(:), expectedHovertext(:));
            try close(); catch; end
        end

        function testScatterWithCustomDataTipTransposed(tc)
            if is_octave()
                return % DataTipTemplate is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            x = [1 2 3];
            y = [4 5 6];
            h = scatter(x, y);
            labels = ["Point1", "Point2", "Point3"]';
            h.DataTipTemplate.DataTipRows(end+1) = dataTipTextRow("ID", labels);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyTrue(isfield(p.data{1}, "hovertext"));
            tc.verifyEqual(p.data{1}.hoverinfo, "text");

            expectedHovertext = "X: " + string(x(:)) + "<br>" + "Y: " ...
                    + string(y(:)) + "<br>" + "ID: " + labels(:) + "<br>";
            tc.verifyEqual(p.data{1}.hovertext(:), expectedHovertext(:));
            try close(); catch; end
        end

        function testPlotDigraph(tc)
            if is_octave()
                return % The `digraph` function is not yet implemented in Octave.
            end
            d = digraph(["Root" "Root" "Child1"], ...
                    ["Child1" "Child2" "Grandchild"]);
            fig = figure("Visible", "off");
            lbl = d.Nodes.Name;
            pt = plot(d, "Layout", "layered", "AssignLayers", "asap", ...
                "EdgeAlpha", 0.4, "ArrowSize", 0, "MarkerSize", 8, ...
                "NodeFontSize", 0.1, "Interpreter", "none");
            text(pt.XData, pt.YData, lbl, "rotation", -22.5, ...
                "FontSize", 12, "Interpreter", "none");
            title("Minimal DAG example");

            p = plotlyfig(fig, "visible", "off");

            % GraphPlot should produce 2 traces: edges + nodes
            tc.verifyGreaterThanOrEqual(numel(p.data), 2);

            % Find the node trace (markers)
            isMarkers = cellfun(@(d) isfield(d, "mode") ...
                    && d.mode == "markers", p.data);
            tc.verifyTrue(any(isMarkers), ...
                "Should have a markers trace for nodes");
            nodeTrace = p.data{find(isMarkers, 1)};
            tc.verifyEqual(numel(nodeTrace.x), numnodes(d));

            % Find the edge trace (lines)
            isLines = cellfun(@(d) isfield(d, "mode") ...
                    && d.mode == "lines", p.data);
            tc.verifyTrue(any(isLines), ...
                "Should have a lines trace for edges");

            % Text annotations should have negated rotation
            textAnns = p.layout.annotations( ...
                    cellfun(@(a) a.textangle ~= 0, p.layout.annotations));
            for k = 1:numel(textAnns)
                tc.verifyEqual(textAnns{k}.textangle, 22.5, ...
                    "Rotation should be negated for graph plot axes");
            end
            try close(); catch; end
        end

        function testPlotDigraphWithMultipleMarkers(tc)
            if is_octave()
                return % The `digraph` function is not yet implemented in Octave.
            end
            d = digraph(["Root" "Root" "Child1"], ...
                    ["Child1" "Child2" "Grandchild"]);
            fig = figure("Visible", "off");
            pt = plot(d, "Layout", "layered", "AssignLayers", "asap", ...
                "EdgeAlpha", 0.4, "ArrowSize", 0, "MarkerSize", 8, ...
                "NodeFontSize", 0.1, "Interpreter", "none");
            markers = ["o" "square" "diamond" "p"];
            for i = 1:numel(markers)
                highlight(pt, i, Marker=markers(i));
            end
            text(pt.XData, pt.YData, d.Nodes.Name, "rotation", -22.5, ...
                "FontSize", 12, "Interpreter", "none");

            p = plotlyfig(fig, "visible", "off");

            isMarkers = cellfun(@(d) isfield(d, "mode") ...
                    && d.mode == "markers", p.data);
            expectedMarkers = ["circle" "square" "diamond" "star"];
            tc.verifyEqual(p.data{isMarkers}.marker.symbol, expectedMarkers);
            try close(); catch; end
        end

        function testDigraphTreeJsonPayloadSize(tc)
            if is_octave()
                return % The `digraph` function is not yet implemented in Octave.
            end
            % Build a 1000-node tree digraph and verify the converted
            % Plotly JSON payload stays within a reasonable size limit.
            nNodes = 1000;
            sources = strings(1, nNodes - 1);
            targets = strings(1, nNodes - 1);
            nodeNames = "N" + (1:nNodes);
            for k = 2:nNodes
                sources(k-1) = nodeNames(floor((k-1)/2) + 1);
                targets(k-1) = nodeNames(k);
            end
            d = digraph(sources, targets);

            fig = figure("Visible", "off");
            plot(d, "Layout", "layered");
            axis off;

            p = plotlyfig(fig, "visible", "off");

            jsonPayload = m2json(p.data) + m2json(p.layout);
            payloadBytes = strlength(jsonPayload);

            maxBytes = 40 * 1024; % 40 KB
            tc.verifyLessThan(payloadBytes, maxBytes, ...
                sprintf("JSON payload is %d bytes, exceeds %d byte limit", ...
                    payloadBytes, maxBytes));
            try close(); catch; end
        end

        function testCustomLegendOrder(tc)
            % Verify that a custom legend order specified via
            % legend(lines(ix),...) is preserved in the Plotly output
            % using the per-trace legendrank property.
            % Traces are created in order C, A, B but the legend is
            % reordered to A, B, C via legendrank.
            legends = {'C' 'A' 'B'};
            customOrderedLegends = {'A' 'B' 'C'};

            fig = figure("Visible","off");
            n = 100;
            rng("default");
            y = cumsum(randn(n,3));
            lines = plot(1:n,y);

            [~,ix] = ismember(customOrderedLegends,legends);
            legend(lines(ix),legends(ix),"Location","northwest","Box","off");

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data,3);

            % Traces stay in original creation order (C, A, B).
            actualNames = cellfun(@(d) char(d.name),p.data,'UniformOutput',false);
            tc.verifyEqual(actualNames,legends, ...
                "Traces must remain in original creation order");

            % legendrank controls the display order in the legend.
            % A=rank 1, B=rank 2, C=rank 3.
            % Trace 1 is "C" -> rank 3, Trace 2 is "A" -> rank 1,
            % Trace 3 is "B" -> rank 2.
            actualRanks = cellfun(@(d) d.legendrank,p.data);
            tc.verifyEqual(actualRanks,[3 1 2], ...
                "legendrank values must order entries as A, B, C");

            % All three traces should be visible in the legend.
            actualShowLegend = cellfun(@(d) d.showlegend,p.data);
            tc.verifyTrue(all(actualShowLegend), ...
                "All traces should have showlegend=true");

            % traceorder must be 'normal' so Plotly honours legendrank.
            tc.verifyEqual(char(p.layout.legend.traceorder),"normal");
            try close(); catch; end
        end

        function testAreaEmptyLegend(tc)
            fig = figure("Visible","off");
            area((1:2)', zeros(2,0));
            try legend({}); catch; end

            p = plotlyfig(fig,"visible","off");

            tc.verifyFalse(p.data{1}.showlegend);
        end

        function testQuiverHovertextData(tc)
            % vector-input quiver emits three traces: the shaft (no
            % hover), a tail marker trace with a per-arrow
            % "(x, y)<br>(u, v)" tooltip, and the arrowhead barbs (no
            % hover).
            fig = figure("Visible","off");
            n = 3;
            X = 1:n;
            Y = [2 4 6];
            U = [3 1 -2];
            V = [4 2 1];
            quiver(X, Y, U, V);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3);
            tc.verifyEqual(p.data{1}.hoverinfo, "skip");
            tc.verifyEqual(p.data{3}.hoverinfo, "skip");
            tc.verifyEqual(p.data{2}.mode, "markers");
            tc.verifyEqual(p.data{2}.hoverinfo, "text");

            [expectedHovertext, nArrows] = Test_plotlyfig_lines.expectedQuiverHovertext(...
                p.data{1}.x, p.data{1}.y);
            tc.verifyEqual(nArrows, n);
            tc.verifyEqual(numel(p.data{2}.x), n);
            tc.verifyEqual(p.data{2}.hovertext, expectedHovertext);
            try close(); catch; end
        end

        function testQuiverGridData(tc)
            % grid-input quiver (every input is a 2D matrix).
            fig = figure("Visible","off");
            n = 3;
            [X, Y] = meshgrid(1:n, 1:n);
            U = ones(n);
            V = ones(n);
            quiver(X, Y, U, V);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3);
            tc.verifyEqual(p.data{1}.hoverinfo, "skip");
            tc.verifyEqual(p.data{3}.hoverinfo, "skip");
            tc.verifyEqual(p.data{2}.mode, "markers");
            tc.verifyEqual(p.data{2}.hoverinfo, "text");

            [expectedHovertext, nArrows] = Test_plotlyfig_lines.expectedQuiverHovertext(...
                p.data{1}.x, p.data{1}.y);
            tc.verifyEqual(nArrows, n*n);
            tc.verifyEqual(numel(p.data{2}.x), n*n);
            tc.verifyEqual(p.data{2}.hovertext, expectedHovertext);
            try close(); catch; end
        end

        function testQuiverNoCoordsData(tc)
            % quiver(u, v) without coordinates draws one arrow per
            % element.
            fig = figure("Visible","off");
            u = [1 2 3 4];
            v = [1 1 2 2];
            quiver(u, v);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3);
            tc.verifyEqual(p.data{1}.hoverinfo, "skip");
            tc.verifyEqual(p.data{3}.hoverinfo, "skip");
            tc.verifyEqual(p.data{2}.mode, "markers");
            tc.verifyEqual(p.data{2}.hoverinfo, "text");

            [expectedHovertext, nArrows] = Test_plotlyfig_lines.expectedQuiverHovertext(...
                p.data{1}.x, p.data{1}.y);
            tc.verifyEqual(nArrows, numel(u));
            tc.verifyEqual(numel(p.data{2}.x), nArrows);
            tc.verifyEqual(p.data{2}.hovertext, expectedHovertext);
            try close(); catch; end
        end

        function testCompassPlotData(tc)
            fig = figure("Visible","off");
            u = [1 2 -1 -2];
            v = [1 -1 1 -1];
            compass(u, v);

            p = plotlyfig(fig,"visible","off");

            % compass converts to 8 scatterpolar traces: 4 arrow shafts
            % (identical on both engines) + 4 arrowheads (geometry
            % differs between engines)
            tc.verifyNumElements(p.data, 8);
            shaftR = {[0 1.4142135623730951], [0 2.2360679774997898], [0 1.4142135623730951], [0 2.2360679774997898]};
            shaftTheta = {[0 45], [0 -26.56505117707799], [0 135], [0 -153.434948822922]};
            shaftText = {'r: 1.41<br>θ: 45.00', 'r: 2.24<br>θ: -26.57', 'r: 1.41<br>θ: 135.00', 'r: 2.24<br>θ: -153.43'};
            if is_octave()
                headR = {[1.4142135623730951 1.1352924243950935 1.4142135623730951 1.1352924243950933], ...
                         [2.2360679774997898 1.7950549357115015 2.2360679774997898 1.7950549357115013], ...
                         [1.4142135623730951 1.1352924243950933 1.4142135623730951 1.1352924243950935], ...
                         [2.2360679774997898 1.7950549357115015 2.2360679774997898 1.7950549357115015]};
                headTheta = {[44.999999999999993 49.763641690726182 44.999999999999993 40.236358309273825], ...
                             [-26.56505117707799 -21.801409486351812 -26.56505117707799 -31.328692867804165], ...
                             [135 139.76364169072619 135 130.23635830927381], ...
                             [-153.434948822922 -148.67130713219584 -153.434948822922 -158.19859051364818]};
            else
                headR = {[1.4142135623730951 1.13701363228415 1.4142135623730951 1.13701363228415], ...
                         [2.2360679774997898 1.79777640433954 2.2360679774997898 1.79777640433954], ...
                         [1.4142135623730951 1.13701363228415 1.4142135623730951 1.13701363228415], ...
                         [2.2360679774997898 1.79777640433954 2.2360679774997898 1.79777640433954]};
                headTheta = {[45 50.7105931374996 45 39.2894068625004], ...
                             [-26.56505117707799 -20.8544580395783 -26.56505117707799 -32.2756443145776], ...
                             [135 140.7105931375 135 129.2894068625], ...
                             [-153.434948822922 -147.724355685422 -153.434948822922 -159.145541960422]};
            end
            for i = 1:4
                tc.verifyEqualStructs(p.data{i}, struct( ...
                    "type", "scatterpolar", ...
                    "subplot", "polar2", ...
                    "visible", true, ...
                    "name", '', ...
                    "mode", 'lines', ...
                    "r", shaftR{i}, ...
                    "theta", shaftTheta{i}, ...
                    "hovertext", {{'' shaftText{i}}}, ...
                    "hoverinfo", "text", ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "width", 0.75, ...
                        "dash", "solid" ...
                    ), ...
                    "marker", struct( ...
                        "size", 3.6, ...
                        "line", struct( ...
                            "width", 0.5 ...
                        ), ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "showlegend", false ...
                ), 'AbsTol', 1e-8);
            end
            for i = 1:4
                tc.verifyEqualStructs(p.data{i+4}, struct( ...
                    "type", "scatterpolar", ...
                    "subplot", "polar2", ...
                    "visible", true, ...
                    "mode", 'lines', ...
                    "r", headR{i}, ...
                    "theta", headTheta{i}, ...
                    "hoverinfo", "skip", ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "width", 0.75, ...
                        "dash", "solid" ...
                    ), ...
                    "marker", struct( ...
                        "size", 3.6, ...
                        "line", struct( ...
                            "width", 0.5 ...
                        ), ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "showlegend", false ...
                ), 'AbsTol', 1e-8);
            end
            try close(); catch; end
        end

        function testFeatherPlotData(tc)
            fig = figure("Visible","off");
            theta = (0:15:360)*pi/180;
            r = 2*cos(2*theta).^2 + 1;
            u = r.*cos(theta);
            v = r.*sin(theta);
            feather(u, v);

            p = plotlyfig(fig,"visible","off");

            if is_octave()
                tc.verifyNumElements(p.data, 51);
            else
                tc.verifyNumElements(p.data, numel(theta)+1);
            end
            expected = struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            );
            if is_octave()
                expected.x = [1 4];
                expected.y = [0 0];
                expected.hoverinfo = PlotlyTestCase.Any();
                expected.hovertext = PlotlyTestCase.Any();
            else
                expected.x = [1 4 NaN 3.4000000000000004 4 3.4000000000000004];
                expected.y = [0 0 NaN 0.23999999999999999 0 -0.23999999999999999];
            end
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testSemilogyPlotData(tc)
            fig = figure("Visible","off");
            x = 0:0.1:10;
            y = x;
            semilogy(x, y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "x", x, ...
                "y", y, ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testSemilogxPlotData(tc)
            fig = figure("Visible","off");
            x = 0:0.1:10;
            y = x;
            semilogx(x, y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "x", x, ...
                "y", y, ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testInvisibleEmptyAxesSkipped(tc)
            % invisible axes that carry no plots (e.g. plotmatrix's
            % full-page outer axes) must not produce data traces.
            fig = figure("Visible","off");
            axes("Visible","off");
            axes();
            plot(1:5, 1:5);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(p.data{1}.x, 1:5);
            try close(); catch; end
        end

        function testFigureBackgroundColors(tc)
            % the native figure and axes background colors must be
            % preserved as paper_bgcolor and plot_bgcolor.
            fig = figure("Visible","off");
            set(fig, "Color", [0.8 0.1 0.1]);
            ax = axes();
            plot(1:5, 1:5);
            set(ax, "Color", [0.1 0.8 0.1]);

            p = plotlyfig(fig,"visible","off");

            tc.verifyEqual(p.layout.paper_bgcolor, "rgb(204,26,26)");
            tc.verifyEqual(p.layout.plot_bgcolor, "rgb(26,204,26)");
            try close(); catch; end
        end

        function testMarkerFaceAutoColor(tc)
            % a filled marker with auto face color must be filled with
            % the line color converted to 0-255, not a hardcoded float
            % rgba default.
            fig = figure("Visible","off");
            plot(1:5, 1:5, "-o", "Color", [0.2 0.6 0.3], "MarkerFaceColor", "auto");

            p = plotlyfig(fig,"visible","off");

            tc.verifyEqual(p.data{1}.marker.color, "rgb(51,153,77)");
            try close(); catch; end
        end

        function testLinePrimitivePlotData(tc)
            % the line() primitive becomes a single lines trace.
            fig = figure("Visible","off");
            x = [0 1 2];
            y = [0 1 0];
            line(x, y, "LineWidth", 2);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "x", x, ...
                "y", y, ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 2, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 2 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            );
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            try close(); catch; end
        end
    end

    methods (Static)
        function [hovertext, nArrows] = expectedQuiverHovertext(shaftX, shaftY, shaftZ)
            %-derive the expected per-arrow tail tooltips from the
            %-shaft trace: one label per NaN-separated 2-point
            %-segment, matching updateQuiver/updateQuivergroup-%
            hovertext = {};
            nArrows = 0;
            n = 1;
            while n < numel(shaftX)
                if isnan(shaftX(n))
                    n = n + 1;
                    continue;
                end
                nArrows = nArrows + 1;
                if nargin >= 3 && ~isempty(shaftZ)
                    hovertext{end+1} = sprintf(...
                        "(%.2f, %.2f, %.2f)<br>(%.2f, %.2f, %.2f)", ...
                        shaftX(n), shaftY(n), shaftZ(n), ...
                        shaftX(n+1)-shaftX(n), shaftY(n+1)-shaftY(n), ...
                        shaftZ(n+1)-shaftZ(n));
                else
                    hovertext{end+1} = sprintf(...
                        "(%.2f, %.2f)<br>(%.2f, %.2f)", ...
                        shaftX(n), shaftY(n), ...
                        shaftX(n+1)-shaftX(n), shaftY(n+1)-shaftY(n));
                end
                n = n + 2;
            end
        end
    end
end
