classdef Test_plotlyfig_bars < PlotlyTestCase
    methods
        function testSingleBarPlotData(tc)
            fig = figure("Visible","off");
            bar(1,1);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "name", '', ...
                "visible", true, ...
                "orientation", "v", ...
                "x", {{1}}, ...
                "y", {{1}}, ...
                "marker", struct( ...
                    "line", struct( ...
                        "width", 0.5, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", true ...
            );
            if is_octave()
                expected.opacity = PlotlyTestCase.AnyNumber();
                expected.showlegend = false;
            else
                expected.marker.line.dash = "solid";
            end
            tc.verifyEqualStructs(p.data{1}, expected);
            try close(); catch; end
        end

        function testDateBarPlotData(tc)
            if is_octave()
                return % Octave's bar does not accept datetime values.
            end
            fig = figure("Visible","off");
            x = datetime("today");
            y = 1;
            bar(x,y)

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "name", '', ...
                "visible", true, ...
                "orientation", "v", ...
                "x", {{convertDate(x)}}, ...
                "y", {{y}}, ...
                "marker", struct( ...
                    "line", struct( ...
                        "width", 0.5, ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "dash", "solid" ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", true ...
            ));
            try close(); catch; end
        end

        function testMultiDateBarData(tc)
            % multiple datetimes on the x axis: convertDate yields a
            % char matrix, kept as-is (renders as an array of date
            % strings)
            if is_octave()
                return % Octave does not support plotting datetime data.
            end
            fig = figure("Visible","off");
            x = datetime(2026,8,1:5);
            y = 1:5;
            bar(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(p.data{1}.x, convertDate(x));
            tc.verifyEqual(p.layout.xaxis1.type, "date");
            try close(); catch; end
        end

        function testVerticalBarPlotData(tc)
            fig = figure("Visible","off");
            x = 1:12;
            y = [38556 24472 14556 18060 19549 8122 28541 7880 3283 4135 7953 1884];
            bar(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "name", '', ...
                "visible", true, ...
                "orientation", "v", ...
                "x", x, ...
                "y", y, ...
                "marker", struct( ...
                    "line", struct( ...
                        "width", 0.5, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", true ...
            );
            if is_octave()
                expected.opacity = PlotlyTestCase.AnyNumber();
                expected.showlegend = false;
                expected.x = x(:);
                expected.y = y(:);
            else
                expected.marker.line.dash = "solid";
            end
            tc.verifyEqualStructs(p.data{1}, expected);
            try close(); catch; end
        end

        function testHorizontalBarPlotData(tc)
            fig = figure("Visible","off");
            x = 1:12;
            y = [38556 24472 14556 18060 19549 8122 28541 7880 3283 4135 7953 1884];
            barh(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "name", '', ...
                "visible", true, ...
                "orientation", "h", ...
                "x", y, ...
                "y", x, ...
                "marker", struct( ...
                    "line", struct( ...
                        "width", 0.5, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", true ...
            );
            if is_octave()
                expected.opacity = PlotlyTestCase.AnyNumber();
                expected.showlegend = false;
                expected.x = y(:);
                expected.y = x(:);
            else
                expected.marker.line.dash = "solid";
            end
            tc.verifyEqualStructs(p.data{1}, expected);
            try close(); catch; end
        end

        function testStackedBarData(tc)
            if is_octave()
                return % Octave's bar does not support the 'stack' option.
            end
            fig = figure("Visible","off");
            data = [10 20 30; 15 25 35; 5 15 25];
            bar(1:3, data, 'stack');

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3); % One for each stack
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "name", '', ...
                "visible", true, ...
                "orientation", "v", ...
                "x", [1 2 3], ...
                "y", [10 15 5], ...
                "marker", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "width", 0.5, ...
                        "dash", "solid" ...
                    ) ...
                ), ...
                "showlegend", true ...
            ));
            tc.verifyEqualStructs(p.data{2}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "name", '', ...
                "visible", true, ...
                "orientation", "v", ...
                "x", [1 2 3], ...
                "y", [20 25 15], ...
                "marker", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "width", 0.5, ...
                        "dash", "solid" ...
                    ) ...
                ), ...
                "showlegend", true ...
            ));
            tc.verifyEqualStructs(p.data{3}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "name", '', ...
                "visible", true, ...
                "orientation", "v", ...
                "x", [1 2 3], ...
                "y", [30 35 25], ...
                "marker", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "width", 0.5, ...
                        "dash", "solid" ...
                    ) ...
                ), ...
                "showlegend", true ...
            ));
            try close(); catch; end
        end

        function testGroupedBarPlotData(tc)
            fig = figure("Visible","off");
            y = [2 5 3; 6 1 4; 3 7 2];
            bar(y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3);
            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "name", '', ...
                "visible", true, ...
                "orientation", "v", ...
                "marker", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString(), ...
                        "width", 0.5 ...
                    ) ...
                ), ...
                "showlegend", true ...
            );
            if is_octave()
                expected.opacity = PlotlyTestCase.AnyNumber();
                expected.showlegend = false;
            else
                expected.marker.line.dash = "solid";
            end

            for i = 1:3
                exp = expected;
                if is_octave()
                    exp.x = [1;2;3];
                    exp.y = y(:,i);
                else
                    exp.x = [1 2 3];
                    exp.y = y(:,i)';
                end
                tc.verifyEqualStructs(p.data{i}, exp);
            end
            try close(); catch; end
        end

        function testMultiGroupBarWidths(tc)
            n = 10;
            mainBars = 0.4*randn(n, 1);
            subBars = 0.4*randn(n, 2);
            iLabel = 1:length(mainBars);

            fig = figure("Visible", "off");
            hold on;
            bar(iLabel', mainBars, 0.95, "facecolor", [0.35 0.35 0.35]);
            bar(iLabel', subBars, 1);

            p = plotlyfig(fig, "visible", "off");

            % 3 traces: 1 wide bar + 2 narrow bars
            tc.verifyNumElements(p.data, 3);

            widths = cellfun(@(d) d.width, p.data);
            wideWidth = max(widths);
            narrowWidth = min(widths);

            if is_octave()
                % Octave renders single-series bars at BarWidth and
                % multi-series bars at BarWidth/nSeries
                tc.verifyGreaterThan(wideWidth, narrowWidth);
            else
                % Wide bar (single series, BarWidth=0.95) should be wider
                % than narrow bars (2 series, BarWidth=1.0)
                tc.verifyGreaterThan(wideWidth, 2 * narrowWidth);
            end

            % Both narrow bars should have the same width
            narrowWidths = widths(widths < wideWidth);
            tc.verifyEqual(narrowWidths(1), narrowWidths(2));

            % All traces should use overlay mode
            tc.verifyEqual(p.layout.barmode, "overlay");
            try close(); catch; end
        end

        function testHistogramPlotData(tc)
            if is_octave()
                return % The `histogram` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            values = [0.6297 0.9559 0.7551 0.5261 0.8501 0.8160 0.1321 0.7607 0.6172 0.3976];
            histogram(values);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "x", [0.15 0.45 0.75 1.05], ...
                "width", [0.3 0.3 0.3 0.3], ...
                "y", [1 2 6 1], ...
                "name", 'values', ...
                "marker", struct( ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "opacity", 0.75, ...
                "visible", true, ...
                "showlegend", true ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testHistogramStairsPlotData(tc)
            if is_octave()
                return % The `histogram` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            values = [0.6297 0.9559 0.7551 0.5261 0.8501 0.8160 0.1321 0.7607 0.6172 0.3976];
            histogram(values,4,DisplayStyle="stairs");

            p = plotlyfig(fig,"visible","off");

            tc.verifyEqualStructs(p.data{1}, struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "scatter", ...
                "mode", "lines", ...
                "x", [0 0 0.24 0.24 0.48 0.48 0.72 0.72 0.96 0.96], ...
                "y", [0 1 1 1 1 3 3 5 5 0], ...
                "name", 'values', ...
                "line", struct( ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "visible", true, ...
                "showlegend", true ...
            ));
            try close(); catch; end
        end

        function testHistPlotData(tc)
            % hist draws its bins as a single bar trace.
            fig = figure("Visible","off");
            x = randn(1000, 1);
            hist(x, 10);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "bar", ...
                "x", PlotlyTestCase.Any(), ...
                "y", PlotlyTestCase.Any(), ...
                "width", PlotlyTestCase.Any(), ...
                "opacity", 1, ...
                "marker", struct( ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "name", 'x', ...
                "visible", true, ...
                "showlegend", true ...
            );
            if is_octave()
                % MATLAB's hist() names the trace after the data
                % variable and shows it in the legend
                expected.name = '';
                expected.showlegend = false;
            end
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testPieChartPlotData(tc)
            fig = figure("Visible","off");
            count = [35 29 28 40 27 30 34 28 36 29 29 30 31 60 90];
            label = 1:15;
            pie(count,label);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 15);
            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", 'scatter', ...
                "name", '', ...
                "visible", true, ...
                "fill", 'tozeroy', ...
                "mode", 'lines', ...
                "marker", struct( ...
                    "sizeref", 1, ...
                    "sizemode", "diameter", ...
                    "size", 6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "showlegend", false ...
            );
            if is_octave()
                expected.x = [-0.01965 -0.01965 -0.08940 -0.15882 -0.22756 -0.29528 -0.36167 -0.40494 -0.01965];
                expected.y = [0.09805 1.09805 1.09561 1.08832 1.07620 1.05931 1.03774 1.02085 0.09805];
                expected.fillcolor = "rgba(68,1,84,1.000000)";
            else
                expected.x = [-0.01965 -0.01965 -0.07612 -0.13241 -0.18835 -0.24374 -0.29842 -0.35221 -0.40494 -0.01965 -0.01965];
                expected.y = [0.09805 1.09805 1.09645 1.09167 1.08372 1.07262 1.05841 1.04113 1.02085 0.09805 0.09805];
                expected.fillcolor = "rgba(62,38,168,1.000000)";
            end
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-4);
            try close(); catch; end
        end

        function testBoxPlotData(tc)
            fig = figure("Visible","off");
            data = [0.4394; -0.0896; 1.0212; -0.8740; 0.4147];
            boxplot(data);

            p = plotlyfig(fig,"visible","off");

            if is_octave()
                tc.verifyNumElements(p.data, 6);
                boxData = { ...
                    [0.6 0.6 0.6 1.4 1.4 1.4 1.4 1.4 0.6 0.6 0.6], ...
                    [0.4147 0.4394 0.4394 0.4394 0.4394 0.4147 0.0432756925294199 -0.0896 -0.0896 0.0432756925294199 0.4147]; ...
                    [1 1], [-0.874 -0.0896]; ...
                    [1 1], [1.0212 0.4394]; ...
                    [0.95 1.05], [-0.874 -0.874]; ...
                    [0.95 1.05], [1.0212 1.0212]; ...
                    [0.6 1.4], [0.4147 0.4147] ...
                };
                for i = 1:6
                    tc.verifyEqualStructs(p.data{i}, struct( ...
                        "type", 'scatter', ...
                        "xaxis", 'x1', ...
                        "yaxis", 'y1', ...
                        "visible", true, ...
                        "name", '', ...
                        "mode", 'lines', ...
                        "x", boxData{i,1}, ...
                        "y", boxData{i,2}, ...
                        "line", struct( ...
                            "color", PlotlyTestCase.AnyColorString(), ...
                            "width", 0.5, ...
                            "dash", "solid" ...
                        ), ...
                        "marker", struct( ...
                            "size", 3.6, ...
                            "line", struct( ...
                                "width", 0.5 ...
                            ), ...
                            "color", PlotlyTestCase.AnyColorString() ...
                        ), ...
                        "showlegend", false ...
                    ), 'AbsTol', 1e-15);
                end
                try close(); catch; end
                return
            end

            tc.verifyNumElements(p.data, 7);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", 'scatter', ...
                "mode", 'markers', ...
                "visible", true, ...
                "name", '', ...
                "xaxis", 'x1', ...
                "yaxis", 'y1', ...
                "x", [NaN NaN], ...
                "y", [NaN NaN], ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "symbol", "cross-thin-open", ...
                    "maxdisplayed", 2, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct(), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqualStructs(p.data{2}, struct( ...
                "type", 'scatter', ...
                "mode", 'lines', ...
                "visible", true, ...
                "name", '', ...
                "xaxis", 'x1', ...
                "yaxis", 'y1', ...
                "x", [0.9250 1.0750], ...
                "y", [0.4147 0.4147], ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqualStructs(p.data{3}, struct( ...
                "type", 'scatter', ...
                "mode", 'lines', ...
                "visible", true, ...
                "name", '', ...
                "xaxis", 'x1', ...
                "yaxis", 'y1', ...
                "x", [0.9250 0.9250 1.0750 1.0750 0.9250], ...
                "y", [-0.2857 0.58485 0.58485 -0.2857 -0.2857], ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqualStructs(p.data{4}, struct( ...
                "type", 'scatter', ...
                "mode", 'lines', ...
                "visible", true, ...
                "name", '', ...
                "xaxis", 'x1', ...
                "yaxis", 'y1', ...
                "x", [0.9625 1.0375], ...
                "y", [-0.874 -0.874], ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqualStructs(p.data{5}, struct( ...
                "type", 'scatter', ...
                "mode", 'lines', ...
                "visible", true, ...
                "name", '', ...
                "xaxis", 'x1', ...
                "yaxis", 'y1', ...
                "x", [0.9625 1.0375], ...
                "y", [1.0212 1.0212], ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqualStructs(p.data{6}, struct( ...
                "type", 'scatter', ...
                "mode", 'lines', ...
                "visible", true, ...
                "name", '', ...
                "xaxis", 'x1', ...
                "yaxis", 'y1', ...
                "x", [1 1], ...
                "y", [-0.874 -0.2857], ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "dash" ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqualStructs(p.data{7}, struct( ...
                "type", 'scatter', ...
                "mode", 'lines', ...
                "visible", true, ...
                "name", '', ...
                "xaxis", 'x1', ...
                "yaxis", 'y1', ...
                "x", [1 1], ...
                "y", [0.58485 1.0212], ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "dash" ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testScatterHistPlotData(tc)
            if is_octave()
                return % The `scatterhist` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            x = [0.15 0.19 0.04 0.64 0.28 0.54 0.70 0.50 0.54 0.45];
            y = [0.12 0.49 0.85 0.87 0.27 0.21 0.56 0.64 0.42 0.21];
            scatterhist(x,y);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", "scatter", ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'markers', ...
                "x", x, ...
                "y", y, ...
                "line", struct(), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "symbol", "circle", ...
                    "maxdisplayed", 11, ...
                    "line", struct( ...
                        "width", 0.5, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqualStructs(p.data{2}, struct( ...
                "xaxis", "x2", ...
                "yaxis", "y2", ...
                "type", "bar", ...
                "name", '', ...
                "x", [1.2 0.8], ...
                "width", [0.5 0.5], ...
                "y", [0.25 0.75], ...
                "orientation", "h", ...
                "marker", struct( ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "opacity", 0.75, ...
                "visible", true, ...
                "showlegend", true ...
            ), 'AbsTol', 1e-15);
            tc.verifyEqualStructs(p.data{3}, struct( ...
                "xaxis", "x3", ...
                "yaxis", "y3", ...
                "type", "bar", ...
                "name", '', ...
                "x", [0.15 0.45 0.75], ...
                "width", [0.3 0.3 0.3], ...
                "y", [4/3 4/3 2/3], ...
                "marker", struct( ...
                    "line", struct( ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "opacity", 0.75, ...
                "visible", true, ...
                "showlegend", true ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testScatterHistPlotLayout(tc)
            if is_octave()
                return % The `scatterhist` function is not yet implemented in Octave.
            end
            fig = figure(Visible="off");
            x = [0.15 0.19 0.04 0.64 0.28 0.54 0.70 0.50 0.54 0.45];
            y = [0.12 0.49 0.85 0.87 0.27 0.21 0.56 0.64 0.42 0.21];
            scatterhist(x,y);

            p = plotlyfig(fig,"visible","off");

            if isMATLABReleaseOlderThan("R2025a")
                figChildren = fig.Children(2:4);
            else
                figChildren = fig.Children(1:3);
            end
            tc.verifyEqual(p.layout.xaxis1.range, [-0.0549, 0.9549], 'AbsTol', 1e-15);
            tc.verifyEqual(p.layout.xaxis1.domain, ...
                    [figChildren(3).Position(1), sum(figChildren(3).Position([1 3]))]);
            tc.verifyEqual(p.layout.xaxis1.anchor, "y1");

            tc.verifyEqual(p.layout.yaxis1.range, [-0.061, 1.061], 'AbsTol', 1e-15);
            tc.verifyEqual(p.layout.yaxis1.domain, ...
                    [figChildren(3).Position(2), sum(figChildren(3).Position([2 4]))]);
            tc.verifyEqual(p.layout.yaxis1.anchor, "x1");

            tc.verifyEqual(p.layout.xaxis2.range, [-0.012, 1.212]);
            tc.verifyEqual(p.layout.xaxis2.domain, ...
                    [figChildren(2).Position(1), sum(figChildren(2).Position([1 3]))]);
            tc.verifyEqual(p.layout.xaxis2.anchor, "y2");

            tc.verifyEqual(p.layout.yaxis2.range, [-0.061, 1.061], 'AbsTol', 1e-15);
            tc.verifyEqual(p.layout.yaxis2.domain, ...
                    [figChildren(2).Position(2), sum(figChildren(2).Position([2 4]))]);
            tc.verifyEqual(p.layout.yaxis2.anchor, "x2");

            tc.verifyEqual(p.layout.xaxis3.range, [-0.0549, 0.9549], 'AbsTol', 1e-15);
            tc.verifyEqual(p.layout.xaxis3.domain, ...
                    [figChildren(1).Position(1), sum(figChildren(1).Position([1 3]))]);
            tc.verifyEqual(p.layout.xaxis3.anchor, "y3");

            tc.verifyEqual(p.layout.yaxis3.range, [-0.013333333333333332, 1.3466666666666667]);
            tc.verifyEqual(p.layout.yaxis3.domain, ...
                    [figChildren(1).Position(2), sum(figChildren(1).Position([2 4]))]);
            tc.verifyEqual(p.layout.yaxis3.anchor, "x3");
            try close(); catch; end
        end

        function testGroupedKernelScatterHistPlotData(tc)
            if is_octave()
                return % The `scatterhist` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            x = [0.15 0.19 0.04 0.64 0.28 0.54 0.70 0.50 0.54 0.45];
            y = [0.12 0.49 0.85 0.87 0.27 0.21 0.56 0.64 0.42 0.21];
            species = [repelem("setosa",4) repelem("versicolor",4) repelem("virginica",2)]';

            scatterhist(x,y,"Group",species,"Kernel","on");

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 11);
            groups = {'setosa' 'versicolor' 'virginica'};
            for i = 1:3
                tc.verifyEqualStructs(p.data{i}, struct( ...
                    "type", "scatter", ...
                    "xaxis", "x1", ...
                    "yaxis", "y1", ...
                    "visible", true, ...
                    "name", groups{i}, ...
                    "mode", 'markers', ...
                    "x", x(species == groups{i}), ...
                    "y", y(species == groups{i}), ...
                    "line", struct(), ...
                    "marker", struct( ...
                        "size", 3.6, ...
                        "symbol", "circle", ...
                        "maxdisplayed", numel(x(species == groups{i})) + 1, ...
                        "line", struct( ...
                            "width", 0.5, ...
                            "color", PlotlyTestCase.AnyColorString() ...
                        ), ...
                        "color", "rgba(0,0,0,0)" ...
                    ), ...
                    "showlegend", true, ...
                    "legendrank", i ...
                ), 'AbsTol', 1e-15);
            end
            % 8 kernel-density line traces: first 4 on the x-axis
            % histogram, last 4 on the y-axis histogram
            for i = 4:7
                tc.verifyEqual(p.data{i}.type, "scatter");
                tc.verifyEqual(p.data{i}.xaxis, "x3");
                tc.verifyEqual(p.data{i}.yaxis, "y3");
                tc.verifyEqual(p.data{i}.mode, "lines");
                tc.verifyEqual(p.data{i}.name, '');
            end
            for i = 8:11
                tc.verifyEqual(p.data{i}.type, "scatter");
                tc.verifyEqual(p.data{i}.xaxis, "x4");
                tc.verifyEqual(p.data{i}.yaxis, "y4");
                tc.verifyEqual(p.data{i}.mode, "lines");
                tc.verifyEqual(p.data{i}.name, '');
            end
            try close(); catch; end
        end
    end
end
