classdef Test_plotlyfig_3d < PlotlyTestCase
    methods
        function testScatter3DPlotData(tc)
            fig = figure("Visible","off");
            [X,Y,Z] = sphere(16);
            x = [0.5*X(:); 0.75*X(:); X(:)]';
            y = [0.5*Y(:); 0.75*Y(:); Y(:)]';
            z = [0.5*Z(:); 0.75*Z(:); Z(:)]';
            scatter3(x,y,z);

            p = plotlyfig(fig,"visible","off");

            if is_octave()
                xData = x(:);
                yData = y(:);
                zData = z(:);
            else
                xData = x;
                yData = y;
                zData = z;
            end

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", "scatter3d", ...
                "scene", "scene1", ...
                "mode", "markers", ...
                "visible", true, ...
                "name", '', ...
                "x", xData, ...
                "y", yData, ...
                "z", zData, ...
                "marker", struct( ...
                    "sizeref", 1, ...
                    "sizemode", "area", ...
                    "size", 72 * ones(size(xData)), ...
                    "line", struct( ...
                        "width", 0.7500, ...
                        "color", PlotlyTestCase.AnyColorString() ...
                    ), ...
                    "symbol", "circle", ...
                    "color", "rgba(0,0,0,0)", ...
                    "opacity", 1 ...
                ), ...
                "showlegend", false ...
            ));
            try close(); catch; end
        end

        function testSurfacePlotData(tc)
            fig = figure("Visible","off");
            points = linspace(-2, 2, 40);
            [x, y] = meshgrid(points, points);
            z = 2./exp((x-0.5).^2+y.^2)-2./exp((x+0.5).^2+y.^2);
            surf(x, y, z)

            p = plotlyfig(fig,"visible","off");

            % both engines: surf emits a scene-based surface plus a
            % scatter3d wireframe trace
            tc.verifyNumElements(p.data, 2);
            tc.verifyEqual(p.data{1}.type, "surface");
            tc.verifyEqual(p.data{1}.scene, "scene1");
            tc.verifyEqual(p.data{1}.contours.x.start, -2);
            tc.verifyEqual(p.data{1}.contours.x.end, 2);
            tc.verifyEqual(p.data{1}.contours.y.start, -2);
            tc.verifyEqual(p.data{1}.contours.y.end, 2);
            tc.verifyEqual(p.data{2}.type, "scatter3d");
            tc.verifyEqual(p.data{2}.mode, "lines");
            tc.verifyEqual(p.data{2}.scene, "scene1");
            try close(); catch; end
        end

        function testPlot3PlotData(tc)
            % plot3 produces a single 3D line trace on scene1.
            fig = figure("Visible","off");
            t = 0:0.1:6*pi;
            x = sin(t);
            y = cos(t);
            z = t;
            plot3(x, y, z);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqualStructs(p.data{1}, struct( ...
                "type", "scatter3d", ...
                "scene", "scene1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines', ...
                "x", x, ...
                "y", y, ...
                "z", z, ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 0.5, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 3.6, ...
                    "line", struct( ...
                        "width", 0.5 ...
                    ), ...
                    "color", PlotlyTestCase.AnyColorString() ...
                ), ...
                "showlegend", false ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testMeshPlotData(tc)
            fig = figure("Visible","off");
            [X,Y] = meshgrid(linspace(-2,2,15));
            Z = X.*exp(-X.^2-Y.^2);
            mesh(X,Y,Z);

            p = plotlyfig(fig,"visible","off");

            % both engines: mesh emits a scene-based surface plus a
            % scatter3d wireframe trace
            tc.verifyNumElements(p.data, 2);
            tc.verifyEqual(p.data{1}.type, "surface");
            tc.verifyEqual(p.data{1}.scene, "scene1");
            tc.verifyEqual(p.data{1}.contours.x.start, -2);
            tc.verifyEqual(p.data{1}.contours.x.end, 2);
            tc.verifyEqual(p.data{1}.contours.y.start, -2);
            tc.verifyEqual(p.data{1}.contours.y.end, 2);
            tc.verifyEqual(p.data{2}.type, "scatter3d");
            tc.verifyEqual(p.data{2}.mode, "lines");
            tc.verifyEqual(p.data{2}.scene, "scene1");
            try close(); catch; end
        end

        function testRibbonPlotData(tc)
            fig = figure("Visible","off");
            n = 50;
            x = linspace(0,4*pi,n);
            y = [sin(x); sin(x)+0.5; sin(x)+1]';
            ribbon(x,y);

            p = plotlyfig(fig,"visible","off");

            % both engines: ribbon emits 3 scene-based surfaces plus
            % 3 scatter3d wireframe traces
            tc.verifyNumElements(p.data, 6);
            for i = 1:3
                tc.verifyEqual(p.data{i}.type, "surface");
                tc.verifyEqual(p.data{i}.scene, "scene1");
            end
            for i = 4:6
                tc.verifyEqual(p.data{i}.type, "scatter3d");
                tc.verifyEqual(p.data{i}.mode, "lines");
                tc.verifyEqual(p.data{i}.scene, "scene1");
            end
            try close(); catch; end
        end

        function testFunctionSurfacePlotData(tc)
            if is_octave()
                return % The `fsurf` function is not yet implemented in Octave.
            end
            fig = figure("Visible","off");
            fsurf(@(x,y) sin(x).*cos(y), [-pi pi -pi pi]);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 2);
            tc.verifyEqual(rmfield(p.data{1}, ["colorscale" "x" "y" "z" "surfacecolor"]), struct( ...
                "scene", "scene1", ...
                "type", "surface", ...
                "opacity", 1, ...
                "name", '{sin}({x}) {cos}({y})', ...
                "showscale", false, ...
                "visible", true, ...
                "showlegend", true ...
            ));
            tc.verifyEqual(rmfield(p.data{2}, ["x" "y" "z"]), struct( ...
                "scene", "scene1", ...
                "type", "scatter3d", ...
                "mode", "lines", ...
                "line", struct( ...
                    "color", "rgb(217,217,217)", ...
                    "width", 1.5, ...
                    "dash", "solid" ...
                ), ...
                "name", '{sin}({x}) {cos}({y})', ...
                "showscale", false, ...
                "visible", true ...
            ));
            try close(); catch; end
        end

        function testIsosurfacePlotData(tc)
            fig = figure("Visible","off");
            [X,Y,Z] = meshgrid(linspace(-1,1,20),linspace(-1,1,20),linspace(-1,1,20));
            V = X.^2 + Y.^2 + Z.^2;
            isosurface(X,Y,Z,V,0.5);

            plotData = get(get(fig, 'children'), 'children');
            plotData = plotData(2);
            p = plotlyfig(fig,"visible","off","treatAs",'isosurface');

            tc.verifyNumElements(p.data, 1);
            vertices = get(plotData, 'Vertices');
            faces = get(plotData, 'Faces');
            expected = struct( ...
                "type", "mesh3d", ...
                "name", '', ...
                "showscale", false, ...
                "x", vertices(:,1), ...
                "y", vertices(:,2), ...
                "z", vertices(:,3), ...
                "i", faces(:,1) - 1, ...
                "j", faces(:,2) - 1, ...
                "k", faces(:,3) - 1, ...
                "color", "rgb(16,190,186)", ...
                "lighting", struct( ...
                    "diffuse", 0.6, ...
                    "ambient", 0.3, ...
                    "specular", 0.9, ...
                    "roughness", 0.2, ...
                    "fresnel", 0.5, ...
                    "vertexnormalsepsilon", 1e-12, ...
                    "facenormalsepsilon", 1e-06 ...
                ), ...
                "scene", "scene1", ...
                "showlegend", false ...
            );
            if is_octave()
                expected.color = "rgb(33,144,141)";
            end
            tc.verifyEqual(p.data{1}, expected);
            try close(); catch; end
        end

        function testContour3PlotData(tc)
            fig = figure("Visible","off");
            [X,Y,Z] = peaks(25);
            contour3(X,Y,Z,20);

            p = plotlyfig(fig,"visible","off");

            if is_octave()
                tc.verifyNumElements(p.data, 1);
                tc.verifyEqual(p.data{1}.type, "scatter3d");
                tc.verifyEqual(p.data{1}.scene, "scene1");
                tc.verifyEqual(p.data{1}.mode, "lines");
                try close(); catch; end
                return
            end

            tc.verifyNumElements(p.data, 1);
            tc.verifyEqual(rmfield(p.data{1}, "colorscale"), struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "name", '', ...
                "type", "surface", ...
                "x", X, ...
                "y", Y, ...
                "z", Z, ...
                "contours", struct( ...
                    "z", struct( ...
                        "end", 7.314565743495028, ...
                        "start", -5.644469721095063, ...
                        "size", 0.682054498136321, ...
                        "show", true, ...
                        "usecolormap", true, ...
                        "width", 1 ...
                    ) ...
                ), ...
                "hidesurface", true, ...
                "visible", true, ...
                "showscale", false, ...
                "reversescale", false, ...
                "showlegend", true ...
            ), 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testBar3PlotData(tc)
            % bar3 emits one mesh3d face trace plus per-bar edge
            % traces on scene1. MATLAB's bar3 draws a surface object
            % that converts to a plain surface trace instead.
            fig = figure("Visible","off");
            bar3(peaks(5)/10);

            p = plotlyfig(fig,"visible","off");

            expected = struct( ...
                "type", "surface", ...
                "scene", "scene1", ...
                "visible", true, ...
                "name", '', ...
                "x", PlotlyTestCase.Any(), ...
                "y", PlotlyTestCase.Any(), ...
                "z", PlotlyTestCase.Any(), ...
                "surfacecolor", PlotlyTestCase.Any(), ...
                "cmax", PlotlyTestCase.Any(), ...
                "cmin", PlotlyTestCase.Any(), ...
                "colorscale", PlotlyTestCase.Any(), ...
                "contours", PlotlyTestCase.Any(), ...
                "lighting", PlotlyTestCase.Any(), ...
                "opacity", PlotlyTestCase.Any(), ...
                "showscale", PlotlyTestCase.Any(), ...
                "showlegend", true ...
            );
            if is_octave()
                % Octave's bar3 patches convert to a mesh3d face
                % trace with per-bar edge traces
                expected = rmfield(expected, ...
                    {'surfacecolor', 'contours', 'lighting', 'opacity'});
                expected.xaxis = "x1";
                expected.yaxis = "y1";
                expected.type = "mesh3d";
                expected.i = PlotlyTestCase.Any();
                expected.j = PlotlyTestCase.Any();
                expected.k = PlotlyTestCase.Any();
                expected.color = PlotlyTestCase.AnyColorString();
                expected.intensity = PlotlyTestCase.Any();
                expected.showscale = false;
                expected.showlegend = false;
            end
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            if is_octave()
                tc.verifyNumElements(p.data, 151);
                tc.verifyEqual(size(p.data{1}.i), [300 1]);
                tc.verifyEqual(p.data{2}.type, "scatter3d");
                tc.verifyEqual(p.data{end}.type, "scatter3d");
            end
            try close(); catch; end
        end

        function testBar3hPlotData(tc)
            % bar3h emits one mesh3d face trace plus per-bar edge
            % traces on scene1. MATLAB's bar3h draws a surface object
            % that converts to a plain surface trace instead.
            fig = figure("Visible","off");
            bar3h(peaks(5)/10);

            p = plotlyfig(fig,"visible","off");

            expected = struct( ...
                "type", "surface", ...
                "scene", "scene1", ...
                "visible", true, ...
                "name", '', ...
                "x", PlotlyTestCase.Any(), ...
                "y", PlotlyTestCase.Any(), ...
                "z", PlotlyTestCase.Any(), ...
                "surfacecolor", PlotlyTestCase.Any(), ...
                "cmax", PlotlyTestCase.Any(), ...
                "cmin", PlotlyTestCase.Any(), ...
                "colorscale", PlotlyTestCase.Any(), ...
                "contours", PlotlyTestCase.Any(), ...
                "lighting", PlotlyTestCase.Any(), ...
                "opacity", PlotlyTestCase.Any(), ...
                "showscale", PlotlyTestCase.Any(), ...
                "showlegend", true ...
            );
            if is_octave()
                % Octave's bar3h patches convert to a mesh3d face
                % trace with per-bar edge traces
                expected = rmfield(expected, ...
                    {'surfacecolor', 'contours', 'lighting', 'opacity'});
                expected.xaxis = "x1";
                expected.yaxis = "y1";
                expected.type = "mesh3d";
                expected.i = PlotlyTestCase.Any();
                expected.j = PlotlyTestCase.Any();
                expected.k = PlotlyTestCase.Any();
                expected.color = PlotlyTestCase.AnyColorString();
                expected.intensity = PlotlyTestCase.Any();
                expected.showscale = false;
                expected.showlegend = false;
            end
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            if is_octave()
                tc.verifyNumElements(p.data, 151);
                tc.verifyEqual(p.data{2}.type, "scatter3d");
                tc.verifyEqual(p.data{end}.type, "scatter3d");
            end
            try close(); catch; end
        end

        function testStem3PlotData(tc)
            % stem3 becomes a single lines+markers scatter3d trace with
            % each stem laid out as a (base, tip, NaN) triple.
            fig = figure("Visible","off");
            t = 0:0.2:6*pi;
            x = cos(t);
            y = sin(t);
            z = t;
            stem3(x, y, z);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 1);
            expected = struct( ...
                "type", "scatter3d", ...
                "scene", "scene1", ...
                "visible", true, ...
                "name", '', ...
                "mode", 'lines+markers', ...
                "x", reshape([x; x; nan(1,length(x))], [], 1), ...
                "y", reshape([y; y; nan(1,length(y))], [], 1), ...
                "z", reshape([zeros(1,length(z)); z; nan(1,length(z))], [], 1), ...
                "line", struct( ...
                    "color", PlotlyTestCase.AnyColorString(), ...
                    "width", 1, ...
                    "dash", "solid" ...
                ), ...
                "marker", struct( ...
                    "size", 2.16, ...
                    "symbol", "circle", ...
                    "line", struct( ...
                        "width", 1, ...
                        "color", PlotlyTestCase.Any() ...
                    ), ...
                    "color", PlotlyTestCase.Any() ...
                ), ...
                "showlegend", false ...
            );
            if is_octave()
                % MATLAB's updateStem doubles the widths and emits
                % column vectors; Octave's updateStemseries does not
                expected.x = reshape([x; x; nan(1,length(x))], 1, []);
                expected.y = reshape([y; y; nan(1,length(y))], 1, []);
                expected.z = reshape([zeros(1,length(z)); z; nan(1,length(z))], 1, []);
                expected.line.width = 0.5;
                expected.marker.size = 3.6;
                expected.marker.line.width = 0.5;
            end
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            try close(); catch; end
        end

        function testPie3PlotData(tc)
            % pie3 converts to face (mesh3d/surface) and edge
            % (scatter3d) traces, all on scene1.
            fig = figure("Visible","off");
            pie3([3 5 2 4 6]);

            p = plotlyfig(fig,"visible","off");

            expected = struct( ...
                "xaxis", "x1", ...
                "yaxis", "y1", ...
                "type", "mesh3d", ...
                "x", PlotlyTestCase.Any(), ...
                "y", PlotlyTestCase.Any(), ...
                "z", PlotlyTestCase.Any(), ...
                "i", PlotlyTestCase.Any(), ...
                "j", PlotlyTestCase.Any(), ...
                "k", PlotlyTestCase.Any(), ...
                "color", PlotlyTestCase.AnyColorString(), ...
                "intensity", PlotlyTestCase.Any(), ...
                "cmin", PlotlyTestCase.Any(), ...
                "cmax", PlotlyTestCase.Any(), ...
                "colorscale", PlotlyTestCase.Any(), ...
                "showscale", false, ...
                "scene", "scene1", ...
                "name", '', ...
                "visible", true, ...
                "showlegend", false, ...
                "hoverinfo", "skip" ...
            );
            tc.verifyEqualStructs(p.data{1}, expected, 'AbsTol', 1e-15);
            if is_octave()
                tc.verifyNumElements(p.data, 30);
            end
            try close(); catch; end
        end

        function testQuiver3VectorData(tc)
            % quiver3 with vector inputs.
            fig = figure("Visible","off");
            n = 3;
            X = 1:n;
            Y = [2 4 6];
            Z = [1 1 1];
            U = [3 1 -2];
            V = [4 2 1];
            W = [1 -1 2];
            quiver3(X, Y, Z, U, V, W);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3);
            tc.verifyEqual(p.data{1}.hoverinfo, "skip");
            tc.verifyEqual(p.data{3}.hoverinfo, "skip");
            tc.verifyEqual(p.data{2}.mode, "markers");
            tc.verifyEqual(p.data{2}.hoverinfo, "text");

            [expectedHovertext, nArrows] = Test_plotlyfig_lines.expectedQuiverHovertext(...
                p.data{1}.x, p.data{1}.y, p.data{1}.z);
            tc.verifyEqual(nArrows, 3);
            tc.verifyEqual(numel(p.data{2}.x), nArrows);
            tc.verifyEqual(p.data{2}.hovertext, expectedHovertext);
            try close(); catch; end
        end

        function testQuiver3GridData(tc)
            % quiver3 with 2D matrix inputs.
            fig = figure("Visible","off");
            n = 2;
            [X, Y] = meshgrid(1:n, 1:n);
            Z = zeros(n);
            U = ones(n);
            V = ones(n);
            W = ones(n);
            quiver3(X, Y, Z, U, V, W);

            p = plotlyfig(fig,"visible","off");

            tc.verifyNumElements(p.data, 3);
            tc.verifyEqual(p.data{1}.hoverinfo, "skip");
            tc.verifyEqual(p.data{3}.hoverinfo, "skip");
            tc.verifyEqual(p.data{2}.mode, "markers");
            tc.verifyEqual(p.data{2}.hoverinfo, "text");

            [expectedHovertext, nArrows] = Test_plotlyfig_lines.expectedQuiverHovertext(...
                p.data{1}.x, p.data{1}.y, p.data{1}.z);
            tc.verifyEqual(nArrows, n*n);
            tc.verifyEqual(numel(p.data{2}.x), n*n);
            tc.verifyEqual(p.data{2}.hovertext, expectedHovertext);
            try close(); catch; end
        end
    end
end
