function updateSceneText(obj, textIndex)
    %-text on a 3D axes (pie3 labels) is anchored in the scene so it
    %-rotates with the view instead of staying pinned to the paper.
    %-The annotation must live under layout.sceneN.annotations: at the
    %-top level plotly ignores the scene refs and draws them as paper,
    %-and gl3d does not draw scatter3d text traces reliably-%
    text_data = obj.State.Text(textIndex).Handle;
    pos = get(text_data, 'Position');
    axIndex = obj.getAxisIndex(obj.State.Text(textIndex).AssociatedAxis);
    sceneKey = sprintf('scene%d', axIndex);

    annotation = struct( ...
        'xref', sceneKey, ...
        'yref', sceneKey, ...
        'zref', sceneKey, ...
        'x', pos(1), 'y', pos(2), 'z', pos(3), ...
        'text', parseString(get(text_data, 'String'), ...
            get(text_data, 'Interpreter')), ...
        'font', struct( ...
            'size', get(text_data, 'FontSize'), ...
            'family', matlab2plotlyfont(get(text_data, 'FontName')), ...
            'color', getStringColor(round(255*get(text_data, 'Color'))) ...
        ), ...
        'showarrow', false, ...
        'xanchor', 'center', ...
        'yanchor', 'middle' ...
    );

    if ~isfield(obj.layout, sceneKey)
        obj.layout.(sceneKey) = struct();
    end
    if ~isfield(obj.layout.(sceneKey), 'annotations')
        obj.layout.(sceneKey).annotations = {};
    end
    obj.layout.(sceneKey).annotations{end+1} = annotation;
end
