function updatePolarAxesLayout(obj, plotIndex)
    axisData = obj.State.Plot(plotIndex).AssociatedAxis;
    if isempty(axisData)
        axisData = get(obj.State.Plot(plotIndex).Handle, 'Parent');
    end

    axIndex = obj.getAxisIndex(axisData);
    xsource = findSourceAxis(obj, axIndex);
    polarName = sprintf('polar%d', xsource+1);

    if is_octave()
        obj.layout.(polarName) = updateOctavePolar(obj, plotIndex);
    else
        obj.layout.(polarName) = updateDefaultPolar(obj, plotIndex);
    end
end

function polarAxis = updateDefaultPolar(obj, plotIndex)
    axisData = obj.State.Plot(plotIndex).AssociatedAxis;
    if isempty(axisData)
        axisData = get(obj.State.Plot(plotIndex).Handle, 'Parent');
    end

    if isprop(axisData, 'ThetaAxis')
        thetaAxis = get(axisData, 'ThetaAxis');
        rAxis = get(axisData, 'RAxis');
    else
        thetaAxis = get(axisData, 'XAxis');
        rAxis = get(axisData, 'YAxis');
    end
    thetaLabel = get(thetaAxis, 'Label');

    tmpPosition = get(axisData, 'Position');
    xo = tmpPosition(1);
    yo = tmpPosition(2);
    w = tmpPosition(3);
    h = tmpPosition(4);

    tickValues = get(rAxis, 'TickValues');
    if isempty(tickValues)
        tickValues = get(axisData, 'YTick');
    end
    zeroIdx = find(tickValues == 0);
    if ~isempty(zeroIdx)
        tickValues = tickValues(zeroIdx(1) + 1 : end);
    end
    rLabel = get(rAxis, 'Label');

    gridColor = getStringColor(255*get(axisData, 'GridColor'), get(axisData, 'GridAlpha'));
    gridWidth = get(axisData, 'LineWidth');
    bgColor = get(axisData, 'Color');
    if isnumeric(bgColor)
        bgColor = getStringColor(round(255*bgColor));
    end
    tmpView = get(axisData, 'View');

    polarAxis.domain = struct( ...
        'x', min([xo xo + w], 1), ...
        'y', min([yo yo + h], 1) ...
    );
    if ischar(bgColor) || isstring(bgColor)
        polarAxis.bgcolor = bgColor;
    end
    polarAxis.angularaxis = struct(...
        'ticklen', 0, ...
        'autorange', true, ...
        'linecolor', gridColor, ...
        'gridwidth', gridWidth, ...
        'gridcolor', gridColor, ...
        'rotation', -tmpView(1), ...
        'showticklabels', true, ...
        'nticks', 16, ...
        'tickfont', struct( ...
            'size', get(thetaAxis, 'FontSize'), ...
            'color', getStringColor(round(255*get(thetaAxis, 'Color'))), ...
            'family', matlab2plotlyfont(get(thetaAxis, 'FontName')) ...
        ), ...
        'title', struct( ...
            'text', get(thetaLabel, 'String'), ...
            'font', struct( ...
                'size', get(thetaLabel, 'FontSize'), ...
                'color', getStringColor(round(255*get(thetaLabel, 'Color'))), ...
                'family', matlab2plotlyfont(get(thetaLabel, 'FontName')) ...
            ) ...
        ) ...
    );
    polarAxis.radialaxis = struct( ...
        'ticklen', 0, ...
        'range', [0, tickValues(end)], ...
        'showline', false, ...
        'angle', 80, ...
        'tickangle', 80, ...
        'gridwidth', gridWidth, ...
        'gridcolor', gridColor, ...
        'showticklabels', true, ...
        'tickvals', tickValues, ...
        'tickfont', struct( ...
            'size', get(rAxis, 'FontSize'), ...
            'color', getStringColor(round(255*get(rAxis, 'Color'))), ...
            'family', matlab2plotlyfont(get(rAxis, 'FontName')) ...
        ), ...
        'title', struct( ...
            'text', get(rLabel, 'String'), ...
            'font', struct( ...
                'size', get(rLabel, 'FontSize'), ...
                'color', getStringColor(round(255*get(rLabel, 'Color'))), ...
                'family', matlab2plotlyfont(get(rLabel, 'FontName')) ...
            ) ...
        ) ...
    );
end

function polarAxis = updateOctavePolar(obj, plotIndex)
    axisData = get(obj.State.Plot(plotIndex).Handle, 'Parent');

    rtick = get(axisData, 'rtick');
    ttick = get(axisData, 'ttick');
    if isempty(rtick)
        rtick = [0 0.5 1];
    end
    if isempty(ttick)
        ttick = 0:30:330;
    end

    gridColor = get(axisData, 'GridColor');
    gridAlpha = 1;
    if isprop(axisData, 'GridAlpha')
        gridAlpha = get(axisData, 'GridAlpha');
    end
    gridColor = getStringColor(round(255*gridColor), gridAlpha);
    gridWidth = get(axisData, 'LineWidth');

    polarAxis.domain = struct( ...
        'x', [0.13 0.905], ...
        'y', [0.11 0.925] ...
    );
    polarAxis.angularaxis = struct( ...
        'ticklen', 0, ...
        'autorange', true, ...
        'linecolor', gridColor, ...
        'gridwidth', gridWidth, ...
        'gridcolor', gridColor, ...
        'rotation', 0, ...
        'direction', 'counterclockwise', ...
        'showticklabels', true, ...
        'nticks', numel(ttick), ...
        'tickfont', struct( ...
            'size', get(axisData, 'FontSize'), ...
            'color', getStringColor(round(255*get(axisData, 'XColor'))), ...
            'family', matlab2plotlyfont(get(axisData, 'FontName')) ...
        ) ...
    );
    polarAxis.radialaxis = struct( ...
        'ticklen', 0, ...
        'range', [0, max(rtick)], ...
        'showline', false, ...
        'gridwidth', gridWidth, ...
        'gridcolor', gridColor, ...
        'showticklabels', true, ...
        'tickvals', rtick, ...
        'tickfont', struct( ...
            'size', get(axisData, 'FontSize'), ...
            'color', getStringColor(round(255*get(axisData, 'YColor'))), ...
            'family', matlab2plotlyfont(get(axisData, 'FontName')) ...
        ) ...
    );
end
